# Go language-pack rule specs (#186). Clean-room, line-detectable Go rules derived from the concepts in
# Effective Go, the Go Code Review Comments wiki, gosec's categories, staticcheck's categories, and CWE —
# our own wording, examples, and detection. Cross-procedural / flow rules (nil-map write, defer-in-loop,
# goroutine loopvar capture, copied Mutex) are AST-tier and tracked separately; these are the precise
# line-regex rules. Parity target for the pack is ~40 (issue #186); this file alone exceeds it.
CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "go")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "go"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


RULES = [
    # ---- inj: injection & untrusted input ----
    r(id="go-sql-string-format", type="vuln", qual="sec", sev="high", cwe="CWE-89", owasp="A03:2021",
      title="SQL built with fmt.Sprintf / string concatenation",
      desc="A SQL statement passed to Query/Exec is assembled with fmt.Sprintf or +, allowing SQL injection.",
      rationale="Interpolating values into SQL text lets an attacker alter the query (CWE-89). Use parameter placeholders ($1, ?) and pass the values as arguments.",
      remediation="Use a parameterized query: db.Query(\"... WHERE id = $1\", id).",
      source="https://cwe.mitre.org/data/definitions/89.html",
      re=r'\.(Query|QueryRow|QueryContext|QueryRowContext|Exec|ExecContext)\(\s*(fmt\.Sprintf|"[^"]*"\s*\+)',
      nc='rows, err := db.Query(fmt.Sprintf("SELECT * FROM users WHERE name = %s", name))',
      c='rows, err := db.Query("SELECT * FROM users WHERE name = $1", name)'),
    r(id="go-command-injection", type="vuln", qual="sec", sev="high", cwe="CWE-78", owasp="A03:2021",
      title="os/exec command built from a formatted or concatenated string",
      desc="exec.Command receives an argument assembled with fmt.Sprintf or +, allowing command injection.",
      rationale="Building a command line from untrusted input lets an attacker inject extra commands (CWE-78). Pass the program and each argument separately, never a formatted string.",
      remediation="Call exec.Command(prog, arg1, arg2) with separate, validated arguments.",
      source="https://cwe.mitre.org/data/definitions/78.html",
      re=r'exec\.Command(Context)?\([^)]*(fmt\.Sprintf|"\s*\+|\+\s*")',
      nc='out, err := exec.Command("sh", "-c", "ls "+dir).Output()',
      c='out, err := exec.Command("ls", dir).Output()'),
    r(id="go-subprocess-shell", type="hotspot", qual="sec", sev="medium", cwe="CWE-78",
      title="Command executed through a shell interpreter",
      desc="exec.Command invokes a shell (sh/bash/cmd) with -c, which re-parses the argument and enables injection.",
      rationale="Running through a shell means the shell re-interprets metacharacters in the argument; review whether the input is fully trusted (CWE-78). Prefer executing the target program directly.",
      remediation="Execute the program directly without a shell, or strictly validate the shell argument.",
      source="https://cwe.mitre.org/data/definitions/78.html",
      re=r'exec\.Command(Context)?\(\s*"(sh|bash|zsh|cmd|powershell)"\s*,\s*"(-c|/c|/C|-Command)"',
      nc='c := exec.Command("bash", "-c", script)',
      c='c := exec.Command("git", "status")'),
    r(id="go-ssrf-request-url", type="vuln", qual="sec", sev="high", cwe="CWE-918",
      title="HTTP request to a URL taken from the incoming request",
      desc="http.Get/Post is called with a URL derived from the inbound request, enabling server-side request forgery.",
      rationale="Fetching a URL an attacker controls lets them reach internal services or metadata endpoints (CWE-918). Validate the target against an allow-list.",
      remediation="Validate/normalize the URL against an allow-list of hosts before fetching.",
      source="https://cwe.mitre.org/data/definitions/918.html",
      re=r'http\.(Get|Post|Head|PostForm)\(\s*(r\.URL|r\.FormValue|r\.Form|req\.URL|c\.Query)',
      nc='resp, err := http.Get(r.FormValue("target"))',
      c='resp, err := http.Get("https://api.internal/health")'),
    r(id="go-path-traversal-servefile", type="vuln", qual="sec", sev="high", cwe="CWE-22",
      title="http.ServeFile with a request-derived path",
      desc="http.ServeFile is passed a path built from the request URL/parameters, allowing directory traversal.",
      rationale="Serving a file whose path comes from the request lets an attacker read arbitrary files via ../ sequences (CWE-22). Clean and confine the path, or use http.FileServer with a restricted root.",
      remediation="Use http.FileServer over a fixed root, or validate the cleaned path stays within the intended directory.",
      source="https://cwe.mitre.org/data/definitions/22.html",
      re=r'http\.ServeFile\([^)]*(r\.URL\.Path|r\.FormValue|vars\[)',
      nc='http.ServeFile(w, r, "./public"+r.URL.Path)',
      c='http.ServeFile(w, r, filepath.Join(root, cleanName))'),
    # ---- crypto: weak crypto & TLS ----
    r(id="go-weak-hash", type="vuln", qual="sec", sev="medium", cwe="CWE-327",
      title="Weak hash function (MD5 or SHA-1)",
      desc="MD5 or SHA-1 is used; both are broken for security purposes.",
      rationale="MD5 and SHA-1 are collision-vulnerable and unfit for signatures, integrity, or password hashing (CWE-327). Use SHA-256+ (or a password KDF).",
      remediation="Use crypto/sha256 or stronger; for passwords use bcrypt/scrypt/argon2.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'(md5|sha1)\.(New|Sum|Sum224|Sum256)?\s*\(',
      nc='h := md5.New()',
      c='h := sha256.New()'),
    r(id="go-des-cipher", type="vuln", qual="sec", sev="high", cwe="CWE-327",
      title="DES / Triple-DES cipher used",
      desc="des.NewCipher / des.NewTripleDESCipher creates a legacy, insecure block cipher.",
      rationale="DES (56-bit) and 3DES are obsolete and considered insecure (CWE-327). Use AES-GCM.",
      remediation="Use crypto/aes with an AEAD mode (e.g. cipher.NewGCM).",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'des\.New(Cipher|TripleDESCipher)\(',
      nc='block, err := des.NewCipher(key)',
      c='block, err := aes.NewCipher(key)'),
    r(id="go-rc4-cipher", type="vuln", qual="sec", sev="high", cwe="CWE-327",
      title="RC4 stream cipher used",
      desc="rc4.NewCipher creates a broken stream cipher.",
      rationale="RC4 has known biases and is insecure (CWE-327). Use AES-GCM or ChaCha20-Poly1305.",
      remediation="Use crypto/aes with GCM, or golang.org/x/crypto/chacha20poly1305.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'rc4\.NewCipher\(',
      nc='c, err := rc4.NewCipher(key)',
      c='aead, err := cipher.NewGCM(block)'),
    r(id="go-rsa-weak-keysize", type="vuln", qual="sec", sev="high", cwe="CWE-326",
      title="RSA key smaller than 2048 bits",
      desc="rsa.GenerateKey is called with a 512- or 1024-bit modulus.",
      rationale="RSA keys under 2048 bits are considered too weak (CWE-326). Generate at least 2048-bit keys.",
      remediation="Generate RSA keys of 2048 bits or more (rsa.GenerateKey(rand.Reader, 2048)).",
      source="https://cwe.mitre.org/data/definitions/326.html",
      re=r'rsa\.GenerateKey\([^,]*,\s*(512|1024)\s*\)',
      nc='key, err := rsa.GenerateKey(rand.Reader, 1024)',
      c='key, err := rsa.GenerateKey(rand.Reader, 2048)'),
    r(id="go-tls-insecure-skip-verify", type="vuln", qual="sec", sev="high", cwe="CWE-295",
      title="TLS certificate verification disabled",
      desc="tls.Config sets InsecureSkipVerify: true, disabling certificate validation.",
      rationale="Skipping verification allows man-in-the-middle attacks (CWE-295). Verify certificates; pin or provide a RootCAs pool if needed.",
      remediation="Remove InsecureSkipVerify (or set it false) and configure RootCAs for custom CAs.",
      source="https://cwe.mitre.org/data/definitions/295.html",
      re=r'InsecureSkipVerify:\s*true',
      nc='cfg := &tls.Config{InsecureSkipVerify: true}',
      c='cfg := &tls.Config{MinVersion: tls.VersionTLS13}'),
    r(id="go-tls-old-version", type="vuln", qual="sec", sev="medium", cwe="CWE-327",
      title="Obsolete TLS minimum version",
      desc="tls.Config pins MinVersion to SSL 3.0 / TLS 1.0 / TLS 1.1.",
      rationale="TLS below 1.2 has known weaknesses and is deprecated (CWE-327). Require TLS 1.2 or 1.3.",
      remediation="Set MinVersion to tls.VersionTLS12 or tls.VersionTLS13.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r'MinVersion:\s*tls\.Version(SSL30|TLS10|TLS11)\b',
      nc='cfg := &tls.Config{MinVersion: tls.VersionTLS10}',
      c='cfg := &tls.Config{MinVersion: tls.VersionTLS12}'),
    r(id="go-math-rand-import", type="hotspot", qual="sec", sev="medium", cwe="CWE-338",
      title="math/rand imported (not for security tokens)",
      desc="The math/rand package is imported; its output is predictable and must not be used for tokens, keys, or IDs.",
      rationale="math/rand is a deterministic PRNG, unsuitable for anything security-sensitive (CWE-338). Review each use; for secrets use crypto/rand.",
      remediation="Use crypto/rand for tokens, salts, keys, and session identifiers.",
      source="https://cwe.mitre.org/data/definitions/338.html",
      re=r'"math/rand"',
      nc='import "math/rand"',
      c='import "crypto/rand"'),
    r(id="go-jwt-none-alg", type="vuln", qual="sec", sev="high", cwe="CWE-347",
      title="JWT signed with the 'none' algorithm",
      desc="jwt.SigningMethodNone disables JWT signature verification.",
      rationale="An unsigned JWT can be forged by anyone (CWE-347). Sign with a real algorithm and reject 'none' on verification.",
      remediation="Use a keyed algorithm (HS256/RS256) and validate the token's algorithm on parse.",
      source="https://cwe.mitre.org/data/definitions/347.html",
      re=r'SigningMethodNone\b',
      nc='s, err := token.SignedString(jwt.SigningMethodNone)',
      c='s, err := token.SignedString(secret)'),
    r(id="go-cors-wildcard-origin", type="hotspot", qual="sec", sev="medium", cwe="CWE-942",
      title="CORS Access-Control-Allow-Origin set to '*'",
      desc="The response allows any origin, which is unsafe when combined with credentials.",
      rationale="A wildcard origin exposes the endpoint to any site (CWE-942); review whether the resource is truly public and never combine it with credentialed requests.",
      remediation="Echo a validated origin from an allow-list instead of '*'.",
      source="https://cwe.mitre.org/data/definitions/942.html",
      re=r'"Access-Control-Allow-Origin"\s*,\s*"\*"',
      nc='w.Header().Set("Access-Control-Allow-Origin", "*")',
      c='w.Header().Set("Access-Control-Allow-Origin", allowedOrigin)'),
    r(id="go-ssh-ignore-hostkey", type="vuln", qual="sec", sev="high", cwe="CWE-322",
      title="SSH host-key verification disabled",
      desc="ssh.InsecureIgnoreHostKey() is used as the HostKeyCallback.",
      rationale="Ignoring the host key allows man-in-the-middle attacks on the SSH connection (CWE-322). Verify the server's key.",
      remediation="Use ssh.FixedHostKey or a known_hosts callback to verify the host key.",
      source="https://cwe.mitre.org/data/definitions/322.html",
      re=r'ssh\.InsecureIgnoreHostKey\(\)',
      nc='cfg.HostKeyCallback = ssh.InsecureIgnoreHostKey()',
      c='cfg.HostKeyCallback = ssh.FixedHostKey(hostKey)'),
    r(id="go-file-world-writable", type="hotspot", qual="sec", sev="medium", cwe="CWE-276",
      title="File or directory created world-writable",
      desc="A file/dir is created with a permission mode granting write to group/other (e.g. 0666, 0777).",
      rationale="World- or group-writable files let other local users tamper with data (CWE-276). Use least-privilege modes like 0600/0700.",
      remediation="Create files as 0600 and directories as 0700 unless broader access is required.",
      source="https://cwe.mitre.org/data/definitions/276.html",
      re=r'os\.(OpenFile|WriteFile|Mkdir|MkdirAll|Chmod)\(.*0o?[0-7][0-7][2367]\)',
      nc='err := os.WriteFile(path, data, 0666)',
      c='err := os.WriteFile(path, data, 0600)'),
    r(id="go-unsafe-pointer", type="hotspot", qual="sec", sev="low", cwe="CWE-119",
      title="unsafe.Pointer used",
      desc="Code uses unsafe.Pointer, bypassing Go's type and memory safety.",
      rationale="unsafe.Pointer defeats the type system and can corrupt memory if misused (CWE-119). Review each use for necessity and correctness.",
      remediation="Avoid unsafe unless required; confine and document it, and prefer safe alternatives.",
      source="https://cwe.mitre.org/data/definitions/119.html",
      re=r'\bunsafe\.Pointer\b',
      nc='p := unsafe.Pointer(&header)',
      c='p := &header'),
    r(id="go-grpc-insecure", type="vuln", qual="sec", sev="medium", cwe="CWE-319",
      title="gRPC dial without transport security",
      desc="grpc.WithInsecure() disables TLS on the gRPC connection.",
      rationale="An insecure gRPC channel transmits data in cleartext (CWE-319). Use transport credentials.",
      remediation="Use grpc.WithTransportCredentials with a TLS config.",
      source="https://cwe.mitre.org/data/definitions/319.html",
      re=r'grpc\.WithInsecure\(\)',
      nc='conn, err := grpc.Dial(addr, grpc.WithInsecure())',
      c='conn, err := grpc.Dial(addr, grpc.WithTransportCredentials(creds))'),
    r(id="go-cookie-insecure", type="hotspot", qual="sec", sev="medium", cwe="CWE-614",
      title="Cookie without the Secure flag",
      desc="An http.Cookie is created with Secure: false, so it may be sent over plaintext HTTP.",
      rationale="A cookie without Secure can leak over an unencrypted connection (CWE-614). Set Secure (and usually HttpOnly).",
      remediation="Set Secure: true (and HttpOnly: true for session cookies).",
      source="https://cwe.mitre.org/data/definitions/614.html",
      re=r'Secure:\s*false',
      nc='http.SetCookie(w, &http.Cookie{Name: "s", Value: v, Secure: false})',
      c='http.SetCookie(w, &http.Cookie{Name: "s", Value: v, Secure: true})'),
    # ---- err: error handling ----
    r(id="go-error-discarded", type="bug", qual="rel", sev="medium", cwe="CWE-252",
      title="Function result assigned to the blank identifier",
      desc="A call's result (often an error) is explicitly discarded with `_ =`.",
      rationale="Discarding a returned error hides failures (CWE-252). Check the error, or document why it is safe to ignore.",
      remediation="Handle the returned error instead of assigning it to _.",
      source="https://cwe.mitre.org/data/definitions/252.html",
      re=r'^\s*_\s*=\s*[\w.]+\(',
      nc='_ = json.Unmarshal(data, &cfg)',
      c='if err := json.Unmarshal(data, &cfg); err != nil { return err }'),
    r(id="go-deferred-close-unchecked", type="smell", qual="maint", sev="low", cwe="CWE-252",
      title="Deferred Close() error ignored",
      desc="A resource is closed with `defer x.Close()`, dropping the error (which matters on writable files).",
      rationale="A failed Close on a writer can mean lost data; the dropped error hides it (CWE-252).",
      remediation="Close in a deferred closure that checks and surfaces the error.",
      source="https://cwe.mitre.org/data/definitions/252.html",
      re=r'^\s*defer\s+\w+\.Close\(\)',
      nc='defer f.Close()',
      c='defer func() { err = errors.Join(err, f.Close()) }()'),
    r(id="go-error-string-capitalized", type="smell", qual="maint", sev="info", cwe="",
      title="Error string starts with a capital letter",
      desc="An error message begins with an uppercase letter, against Go convention (errors are often wrapped).",
      rationale="Go error strings should not be capitalized because they are frequently embedded mid-sentence when wrapped (Go Code Review Comments — Error Strings).",
      remediation="Start error strings with a lowercase letter and no trailing punctuation.",
      source="https://go.dev/wiki/CodeReviewComments#error-strings",
      re=r'(errors\.New|fmt\.Errorf)\("[A-Z]',
      nc='return errors.New("Cannot open config file")',
      c='return errors.New("cannot open config file")'),
    r(id="go-error-string-punctuation", type="smell", qual="maint", sev="info", cwe="",
      title="Error string ends with punctuation",
      desc="An error message ends with a period or exclamation mark, against Go convention.",
      rationale="Trailing punctuation reads badly when the error is wrapped into a larger message (Go Code Review Comments — Error Strings).",
      remediation="Remove trailing punctuation from error strings.",
      source="https://go.dev/wiki/CodeReviewComments#error-strings",
      re=r'(errors\.New|fmt\.Errorf)\("[^"]*[.!]"\)',
      nc='return errors.New("cannot open config file.")',
      c='return errors.New("cannot open config file")'),
    r(id="go-empty-error-text", type="bug", qual="rel", sev="low", cwe="",
      title="Error created with an empty message",
      desc="errors.New(\"\") or fmt.Errorf(\"\") produces an error with no text.",
      rationale="An empty error message gives no diagnostic information at the failure site.",
      remediation="Provide a descriptive message (and wrap the cause with %w).",
      source="https://go.dev/blog/go1.13-errors",
      re=r'(errors\.New|fmt\.Errorf)\(""\)',
      nc='return fmt.Errorf("")',
      c='return fmt.Errorf("parse config: %w", err)'),
    r(id="go-errorf-verb-not-wrap", type="smell", qual="maint", sev="low", cwe="",
      title="Error wrapped with %v/%s instead of %w",
      desc="fmt.Errorf formats an error with %v or %s, so errors.Is/As can no longer unwrap it.",
      rationale="Using %w preserves the error chain for errors.Is/As; %v/%s flatten it to text (Go 1.13 errors).",
      remediation="Wrap the cause with %w: fmt.Errorf(\"...: %w\", err).",
      source="https://go.dev/blog/go1.13-errors",
      re=r'fmt\.Errorf\("[^"]*%[sv]"?[^"]*",\s*err\)',
      nc='return fmt.Errorf("read config: %v", err)',
      c='return fmt.Errorf("read config: %w", err)'),
    r(id="go-error-compare-string", type="bug", qual="rel", sev="medium", cwe="",
      title="Error compared by its string message",
      desc="Code compares err.Error() to a literal string to detect a specific error.",
      rationale="Matching on the message text is brittle and breaks when wording changes or the error is wrapped; use errors.Is/As with sentinel or typed errors.",
      remediation="Use errors.Is(err, ErrX) or errors.As for a typed error.",
      source="https://go.dev/blog/go1.13-errors",
      re=r'\.Error\(\)\s*(==|!=)\s*"',
      nc='if err.Error() == "not found" {',
      c='if errors.Is(err, ErrNotFound) {'),
    r(id="go-log-fatal-in-code", type="smell", qual="maint", sev="medium", cwe="",
      title="log.Fatal used outside main/init",
      desc="log.Fatal/Fatalf/Fatalln calls os.Exit, terminating the process from library code.",
      rationale="log.Fatal exits the whole program and skips deferred cleanup; only top-level main/init should decide to terminate.",
      remediation="Return an error and let the caller decide; reserve log.Fatal for main.",
      source="https://pkg.go.dev/log#Fatal",
      re=r'\blog\.(Fatal|Fatalf|Fatalln)\(',
      nc='log.Fatalf("cannot connect: %v", err)',
      c='return fmt.Errorf("cannot connect: %w", err)'),
    r(id="go-log-panic", type="smell", qual="maint", sev="medium", cwe="",
      title="log.Panic used for control flow",
      desc="log.Panic/Panicf/Panicln logs and then panics.",
      rationale="Panicking for ordinary error conditions crashes the goroutine; return an error instead.",
      remediation="Return an error rather than log.Panic for recoverable conditions.",
      source="https://pkg.go.dev/log#Panic",
      re=r'\blog\.(Panic|Panicf|Panicln)\(',
      nc='log.Panic("unexpected state")',
      c='return errors.New("unexpected state")'),
    # ---- bugs: correctness ----
    r(id="go-bool-literal-compare", type="smell", qual="maint", sev="low", cwe="",
      title="Boolean compared to a literal true/false",
      desc="A boolean expression is compared with == true or == false.",
      rationale="Comparing a bool to a literal is redundant and error-prone; use the boolean directly (or its negation).",
      remediation="Write `if ok` / `if !ok` instead of `== true` / `== false`.",
      source="https://staticcheck.dev/docs/checks/#S1002",
      re=r'(==|!=)\s*(true|false)\b',
      nc='if enabled == true {',
      c='if enabled {'),
    r(id="go-unchecked-type-assertion", type="bug", qual="rel", sev="medium", cwe="",
      title="Type assertion without the comma-ok form",
      desc="A single-result type assertion x.(T) panics at runtime if the dynamic type does not match.",
      rationale="The one-value form panics on a type mismatch; the comma-ok form lets the code handle it (Effective Go — interface conversions).",
      remediation="Use `v, ok := x.(T)` and handle ok == false.",
      source="https://go.dev/doc/effective_go#interface_conversions",
      re=r'^\s*\w+\s*:?=\s*[\w.]+\.\(\*?[\w.]+\)\s*$',
      nc='cfg := v.(*Config)',
      c='cfg, ok := v.(*Config)'),
    r(id="go-append-result-ignored", type="bug", qual="rel", sev="medium", cwe="",
      title="Result of append() discarded",
      desc="append is called as a statement without assigning its result back.",
      rationale="append may return a new slice header; ignoring the result silently loses the appended elements.",
      remediation="Assign the result: s = append(s, x).",
      source="https://go.dev/doc/effective_go#append",
      re=r'^\s*append\(',
      nc='append(items, next)',
      c='items = append(items, next)'),
    r(id="go-context-todo", type="smell", qual="maint", sev="low", cwe="",
      title="context.TODO() left in code",
      desc="context.TODO() marks a place where a real context was not yet plumbed through.",
      rationale="TODO contexts signal unfinished wiring; a request-scoped context should be threaded from the caller (Go context guidance).",
      remediation="Accept and pass a context.Context parameter from the caller.",
      source="https://go.dev/blog/context",
      re=r'context\.TODO\(\)',
      nc='ctx := context.TODO()',
      c='ctx := r.Context()'),
    r(id="go-deprecated-ioutil", type="smell", qual="maint", sev="low", cwe="",
      title="Deprecated io/ioutil package used",
      desc="The io/ioutil package is deprecated as of Go 1.16.",
      rationale="io/ioutil functions were moved to os and io in Go 1.16; the package is deprecated.",
      remediation="Use the os / io replacements (e.g. os.ReadFile, io.ReadAll).",
      source="https://pkg.go.dev/io/ioutil",
      re=r'\bioutil\.',
      nc='data, err := ioutil.ReadFile(path)',
      c='data, err := os.ReadFile(path)'),
    r(id="go-http-client-no-timeout", type="bug", qual="rel", sev="medium", cwe="",
      title="http.Client created without a timeout",
      desc="An http.Client is constructed with no Timeout, so a slow server can hang the request forever.",
      rationale="The zero-value http.Client has no timeout; a stuck connection blocks the goroutine indefinitely (reliability).",
      remediation="Set a Timeout on the client, or use a context with a deadline.",
      source="https://pkg.go.dev/net/http#Client",
      re=r'&?http\.Client\{\s*\}',
      nc='client := &http.Client{}',
      c='client := &http.Client{Timeout: 10 * time.Second}'),
    r(id="go-panic-in-code", type="smell", qual="maint", sev="medium", cwe="",
      title="panic() used for an ordinary error",
      desc="panic is called in normal code flow instead of returning an error.",
      rationale="Panicking crashes the goroutine and is reserved for truly unrecoverable states; ordinary failures should return an error (Effective Go).",
      remediation="Return an error to the caller instead of panicking.",
      source="https://go.dev/doc/effective_go#panic",
      re=r'^\s*panic\(',
      nc='panic("config missing")',
      c='return errors.New("config missing")'),
    r(id="go-time-format-layout", type="bug", qual="rel", sev="medium", cwe="",
      title="Non-Go reference layout in time formatting",
      desc="A time layout uses YYYY/DD/hh style tokens instead of Go's reference time (2006-01-02 15:04:05).",
      rationale="Go time layouts use the specific reference date, not yyyy/DD tokens; the wrong tokens format times incorrectly.",
      remediation='Use the Go reference time, e.g. "2006-01-02 15:04:05".',
      source="https://pkg.go.dev/time#pkg-constants",
      re=r'\.Format\("[^"]*(YYYY|yyyy|DD|hh:mm|MM/DD)',
      nc='s := t.Format("YYYY-MM-DD")',
      c='s := t.Format("2006-01-02")'),
    r(id="go-rand-seed-deprecated", type="smell", qual="maint", sev="low", cwe="",
      title="rand.Seed used (deprecated in Go 1.20)",
      desc="math/rand's top-level Seed is deprecated; the global generator is auto-seeded since Go 1.20.",
      rationale="rand.Seed is deprecated; seeding the global source is unnecessary and, with a fixed seed, harmful to randomness.",
      remediation="Drop rand.Seed, or use rand.New(rand.NewSource(seed)) for a local generator.",
      source="https://pkg.go.dev/math/rand#Seed",
      re=r'\brand\.Seed\(',
      nc='rand.Seed(time.Now().UnixNano())',
      c='r := rand.New(rand.NewSource(seed))'),
    r(id="go-errors-new-sprintf", type="smell", qual="maint", sev="low", cwe="",
      title="errors.New(fmt.Sprintf(...)) instead of fmt.Errorf",
      desc="An error message is formatted with fmt.Sprintf and wrapped in errors.New.",
      rationale="fmt.Errorf does the same in one call and supports %w wrapping; errors.New(fmt.Sprintf(...)) is redundant (staticcheck S1028).",
      remediation="Use fmt.Errorf(...) directly.",
      source="https://staticcheck.dev/docs/checks/#S1028",
      re=r'errors\.New\(fmt\.Sprintf\(',
      nc='return errors.New(fmt.Sprintf("id %d not found", id))',
      c='return fmt.Errorf("id %d not found", id)'),
    r(id="go-sprintf-single-string", type="smell", qual="maint", sev="low", cwe="",
      title='fmt.Sprintf("%s", x) with a single string argument',
      desc='fmt.Sprintf("%s", x) is a no-op formatting of a value that is already a string.',
      rationale="Formatting a lone %s just returns the argument; it wastes an allocation and obscures intent (staticcheck S1025).",
      remediation="Use the value directly (or x.String() if x is a Stringer).",
      source="https://staticcheck.dev/docs/checks/#S1025",
      re=r'fmt\.Sprintf\("%s",\s*\w+\)',
      nc='name := fmt.Sprintf("%s", raw)',
      c='name := raw'),
    r(id="go-todo-marker", type="smell", qual="maint", sev="info", cwe="", skip="skipGoTodoMarker",
      title="TODO/FIXME marker (tracked debt)",
      desc="A TODO/FIXME/XXX/HACK comment marks unfinished work.",
      rationale="Such markers record known, incomplete work; surfacing them as tracked technical debt keeps them from being forgotten (ISO/IEC 25010 maintainability).",
      remediation="Resolve the item or link it to a tracked issue.",
      source="https://go.dev/wiki/CodeReviewComments",
      re=r'\b(TODO|FIXME|XXX|HACK)\b',
      nc='// TODO: handle the reconnect case',
      c='// reconnect handling is implemented below'),
    r(id="go-context-in-struct", type="smell", qual="maint", sev="low", cwe="",
      title="context.Context stored in a struct field",
      desc="A context.Context is kept as a struct field instead of being passed per call.",
      rationale="Contexts are request-scoped and should flow as the first function argument, not be stored on a long-lived struct (Go context guidance).",
      remediation="Pass ctx context.Context as the first parameter of the methods that need it.",
      source="https://go.dev/blog/context-and-structs",
      re=r'^\s*\w+\s+context\.Context\s*$',
      nc='	ctx context.Context',
      c='func (s *Server) Do(ctx context.Context) error {'),
    r(id="go-fmt-print-in-code", type="smell", qual="maint", sev="low", cwe="",
      title="fmt.Print/Println used instead of a logger",
      desc="fmt.Print/Println/Printf writes to stdout, bypassing the logging framework.",
      rationale="Direct stdout writes cannot be leveled, routed, or disabled in production; use the application logger.",
      remediation="Log through the application's structured logger.",
      source="https://pkg.go.dev/log/slog",
      re=r'\bfmt\.(Print|Println|Printf)\(',
      nc='fmt.Println("starting worker", id)',
      c='logger.Info("starting worker", "id", id)'),
]
