CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "py")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "python", "security"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


# Python security pack (line-regex tier): precise, Bandit-family sink patterns. Each keys off a
# specific dotted call / keyword so the regex is well-anchored and low-false-positive. Concept
# origins cited (CWE, OWASP, Bandit test IDs, PyPA/Django/Flask docs); prose is authored clean-room.
# Deliberately omits known-noisy heuristics (bare random.*, generic string-format SQL).
RULES = [
    r(id="python-eval-call", type="hotspot", qual="sec", sev="high", cwe="CWE-95", owasp="A03:2021",
      title="Use of eval()", desc="eval() executes an arbitrary string as Python code.",
      rationale="Evaluating any attacker-influenced string with eval runs arbitrary code.",
      remediation="Use ast.literal_eval for literals, or an explicit parser / lookup.",
      source="https://cwe.mitre.org/data/definitions/95.html",
      re=r"\beval\s*\(", nc="result = eval(user_data)", c="result = ast.literal_eval(user_data)"),
    r(id="python-exec-call", type="hotspot", qual="sec", sev="high", cwe="CWE-95", owasp="A03:2021",
      title="Use of exec()", desc="exec() runs a string as Python statements.",
      rationale="exec on attacker-influenced input executes arbitrary code.",
      remediation="Avoid exec; dispatch through a whitelist of known callables.",
      source="https://cwe.mitre.org/data/definitions/95.html",
      re=r"\bexec\s*\(", nc='exec(compile(src, "<s>", "exec"))', c="handler = registry[name]"),
    r(id="python-os-system", type="hotspot", qual="sec", sev="medium", cwe="CWE-78", owasp="A03:2021",
      title="os.system() command execution", desc="os.system runs a command through the shell.",
      rationale="os.system passes its string to the shell, enabling command injection.",
      remediation="Use subprocess.run([...], shell=False) with an argument list.",
      source="https://cwe.mitre.org/data/definitions/78.html",
      re=r"\bos\.system\s*\(", nc="os.system(cmd)", c="subprocess.run([cmd], shell=False)"),
    r(id="python-os-popen", type="hotspot", qual="sec", sev="medium", cwe="CWE-78", owasp="A03:2021",
      title="os.popen() command execution", desc="os.popen runs a command through the shell.",
      rationale="os.popen invokes the shell on its string argument, enabling injection.",
      remediation="Use subprocess with an argument list and shell=False.",
      source="https://cwe.mitre.org/data/definitions/78.html",
      re=r"\bos\.popen\s*\(", nc="stream = os.popen(cmd)", c="proc = subprocess.Popen(args)"),
    r(id="python-pickle-load", type="hotspot", qual="sec", sev="medium", cwe="CWE-502", owasp="A08:2021",
      title="pickle deserialization", desc="pickle.load/loads can execute arbitrary code from crafted data.",
      rationale="Unpickling untrusted data invokes __reduce__ and can run arbitrary code.",
      remediation="Use a safe format such as JSON for untrusted data.",
      source="https://cwe.mitre.org/data/definitions/502.html",
      re=r"\bpickle\.loads?\s*\(", nc="obj = pickle.loads(blob)", c="obj = json.loads(blob)"),
    r(id="python-marshal-load", type="hotspot", qual="sec", sev="medium", cwe="CWE-502", owasp="A08:2021",
      title="marshal deserialization", desc="marshal.load/loads is unsafe for untrusted data.",
      rationale="marshal is not intended for untrusted input and can crash or misbehave.",
      remediation="Use a safe, documented format like JSON.",
      source="https://cwe.mitre.org/data/definitions/502.html",
      re=r"\bmarshal\.loads?\s*\(", nc="obj = marshal.loads(data)", c="obj = json.loads(data)"),
    r(id="python-hashlib-md5", type="hotspot", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="MD5 via hashlib", desc="hashlib.md5 is unfit for security use.",
      rationale="MD5 is collision-prone; do not use it for signatures, tokens, or integrity.",
      remediation="Use hashlib.sha256 (or pass usedforsecurity=False only for non-security checksums).",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r"\bhashlib\.md5\s*\(", nc="digest = hashlib.md5(data)", c="digest = hashlib.sha256(data)"),
    r(id="python-hashlib-sha1", type="hotspot", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="SHA-1 via hashlib", desc="hashlib.sha1 is deprecated for security use.",
      rationale="SHA-1 has practical collisions; avoid it for security purposes.",
      remediation="Use hashlib.sha256 or stronger.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r"\bhashlib\.sha1\s*\(", nc="digest = hashlib.sha1(data)", c="digest = hashlib.sha256(data)"),
    r(id="python-ssl-unverified-context", type="vuln", qual="sec", sev="high", cwe="CWE-295", owasp="A07:2021",
      title="Unverified TLS context", desc="ssl._create_unverified_context disables certificate validation.",
      rationale="An unverified context accepts any certificate, enabling MITM.",
      remediation="Use ssl.create_default_context(), which verifies certificates.",
      source="https://cwe.mitre.org/data/definitions/295.html",
      re=r"ssl\._create_unverified_context\s*\(", nc="ctx = ssl._create_unverified_context()",
      c="ctx = ssl.create_default_context()"),
    r(id="python-requests-verify-false", type="vuln", qual="sec", sev="high", cwe="CWE-295", owasp="A07:2021",
      title="TLS verification disabled", desc="verify=False disables certificate checking in requests/httpx.",
      rationale="Disabling verification accepts any certificate, enabling MITM.",
      remediation="Leave verification on; pass a CA bundle path if you need a custom trust store.",
      source="https://cwe.mitre.org/data/definitions/295.html",
      # PyJWT's decode() takes the same keyword to mean "skip claim validation", which is a
      # different (and non-TLS) setting, so that call is filtered out in skipJWTVerifyFlag.
      skip="skipJWTVerifyFlag",
      re=r"verify\s*=\s*False\b", nc="resp = requests.get(url, verify=False)", c="resp = requests.get(url, verify=True)"),
    r(id="python-flask-debug", type="hotspot", qual="sec", sev="medium", cwe="CWE-489", owasp="A05:2021",
      title="Flask debug mode enabled", desc="app.run(debug=True) exposes the Werkzeug debugger (RCE).",
      rationale="The interactive debugger allows arbitrary code execution if reachable in production.",
      remediation="Never run with debug=True in production; gate it behind an env flag.",
      source="https://cwe.mitre.org/data/definitions/489.html",
      re=r"\.run\s*\([^)]*debug\s*=\s*True", nc='app.run(host="0.0.0.0", debug=True)', c='app.run(host="127.0.0.1")'),
    r(id="python-django-debug", type="hotspot", qual="sec", sev="medium", cwe="CWE-489", owasp="A05:2021",
      title="Django DEBUG enabled", desc="DEBUG = True leaks stack traces and settings in responses.",
      rationale="Running Django with DEBUG on discloses sensitive details to clients.",
      remediation="Set DEBUG = False in production settings.",
      source="https://cwe.mitre.org/data/definitions/489.html",
      re=r"^\s*DEBUG\s*=\s*True\b", nc="DEBUG = True", c="DEBUG = False"),
    r(id="python-jinja-autoescape-off", type="vuln", qual="sec", sev="medium", cwe="CWE-79", owasp="A03:2021",
      title="Jinja2 autoescape disabled", desc="autoescape=False renders unescaped HTML, enabling XSS.",
      rationale="Disabling autoescape lets untrusted template values inject markup.",
      remediation="Use autoescape=True (or select_autoescape).",
      source="https://cwe.mitre.org/data/definitions/79.html",
      re=r"autoescape\s*=\s*False\b", nc="env = Environment(autoescape=False)", c="env = Environment(autoescape=True)"),
    r(id="python-xml-parse-xxe", type="hotspot", qual="sec", sev="medium", cwe="CWE-611", owasp="A05:2021",
      title="XML parsed with the standard library", desc="xml.etree parsing is vulnerable to XXE and entity-expansion attacks.",
      rationale="The stdlib XML parsers resolve external entities on untrusted input.",
      remediation="Use the defusedxml package for untrusted XML.",
      source="https://cwe.mitre.org/data/definitions/611.html",
      re=r"\betree\.(parse|fromstring)\s*\(", nc="tree = etree.parse(user_file)", c="tree = safe_parse(user_file)"),
    r(id="python-paramiko-autoadd-policy", type="hotspot", qual="sec", sev="medium", cwe="CWE-295", owasp="A07:2021",
      title="Paramiko AutoAddPolicy", desc="AutoAddPolicy accepts unknown SSH host keys, defeating host verification.",
      rationale="Auto-adding host keys allows MITM on the first (or any new) connection.",
      remediation="Use RejectPolicy and manage known_hosts explicitly.",
      source="https://cwe.mitre.org/data/definitions/295.html",
      re=r"\bAutoAddPolicy\s*\(", nc="client.set_missing_host_key_policy(paramiko.AutoAddPolicy())",
      c="client.set_missing_host_key_policy(paramiko.RejectPolicy())"),
    r(id="python-telnetlib", type="hotspot", qual="sec", sev="low", cwe="CWE-319", owasp="A02:2021",
      title="Cleartext Telnet protocol", desc="telnetlib transmits credentials and data in cleartext.",
      rationale="Telnet has no transport encryption; traffic can be read and modified.",
      remediation="Use SSH (e.g. paramiko) instead of Telnet.",
      source="https://cwe.mitre.org/data/definitions/319.html",
      re=r"\btelnetlib\b", nc="import telnetlib", c="import paramiko"),
    r(id="python-ftplib-cleartext", type="hotspot", qual="sec", sev="low", cwe="CWE-319", owasp="A02:2021",
      title="Cleartext FTP protocol", desc="ftplib (plain FTP) transmits credentials and data in cleartext.",
      rationale="Plain FTP has no transport encryption; use FTPS or SFTP.",
      remediation="Use ftplib.FTP_TLS or an SFTP client.",
      source="https://cwe.mitre.org/data/definitions/319.html",
      re=r"\bftplib\b", nc="import ftplib", c="import paramiko"),
    r(id="python-hardcoded-tmp-path", type="hotspot", qual="sec", sev="low", cwe="CWE-377", owasp="A01:2021",
      title="Hardcoded /tmp path", desc="A literal /tmp path is predictable and world-writable, inviting races.",
      rationale="Fixed temp paths under /tmp enable symlink and race attacks.",
      remediation="Use tempfile.mkstemp / NamedTemporaryFile / gettempdir().",
      source="https://cwe.mitre.org/data/definitions/377.html",
      re=r"[\"']/tmp/", nc='lock = "/tmp/session.lock"', c="lock = tempfile.gettempdir()"),
    r(id="python-django-mark-safe", type="hotspot", qual="sec", sev="medium", cwe="CWE-79", owasp="A03:2021",
      title="Django mark_safe", desc="mark_safe tells the template engine not to escape the value.",
      rationale="Marking untrusted content safe disables escaping and causes XSS.",
      remediation="Escape the value, or use format_html with placeholders.",
      source="https://cwe.mitre.org/data/definitions/79.html",
      re=r"\bmark_safe\s*\(", nc="html = mark_safe(user_input)", c="html = escape(user_input)"),
    r(id="python-django-raw-sql", type="hotspot", qual="sec", sev="medium", cwe="CWE-89", owasp="A03:2021",
      title="Django raw SQL query", desc="QuerySet.raw executes a raw SQL string.",
      rationale="A raw query built from input is vulnerable to SQL injection.",
      remediation="Use the ORM, or pass parameters via the params= argument.",
      source="https://cwe.mitre.org/data/definitions/89.html",
      re=r"\.raw\s*\(", nc="qs = User.objects.raw(query)", c="qs = User.objects.filter(name=name)"),
    r(id="python-os-chmod-world", type="hotspot", qual="sec", sev="medium", cwe="CWE-732", owasp="A01:2021",
      title="World-accessible chmod", desc="chmod 0o777 grants read/write/execute to every user.",
      rationale="Mode 0o777 gives all users full access to the file.",
      remediation="Grant the least permission needed (e.g. 0o600 / 0o640).",
      source="https://cwe.mitre.org/data/definitions/732.html",
      re=r"os\.chmod\s*\([^)]*0o?777", nc="os.chmod(path, 0o777)", c="os.chmod(path, 0o600)"),
    r(id="python-crypto-des", type="vuln", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="DES cipher (PyCryptodome)", desc="DES has a 56-bit key and is trivially brute-forced.",
      rationale="DES is far too weak for modern use; use AES.",
      remediation="Use AES (e.g. AES.new(key, AES.MODE_GCM)).",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r"\bDES\.new\s*\(", nc="cipher = DES.new(key, DES.MODE_CBC)", c="cipher = AES.new(key, AES.MODE_GCM)"),
    r(id="python-crypto-arc4", type="vuln", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="RC4 cipher (PyCryptodome)", desc="ARC4/RC4 has known keystream biases and is prohibited.",
      rationale="RC4 biases allow plaintext recovery; it is banned in TLS.",
      remediation="Use AES-GCM instead of ARC4.",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r"\bARC4\.new\s*\(", nc="cipher = ARC4.new(key)", c="cipher = AES.new(key, AES.MODE_GCM, nonce)"),
    r(id="python-ssl-insecure-protocol", type="vuln", qual="sec", sev="medium", cwe="CWE-327", owasp="A02:2021",
      title="Insecure SSL/TLS protocol constant", desc="PROTOCOL_SSLv2/SSLv3/TLSv1 select broken or deprecated protocols.",
      rationale="SSLv2/SSLv3 are broken and TLSv1.0 is deprecated (RFC 8996).",
      remediation="Use PROTOCOL_TLS_CLIENT / PROTOCOL_TLS_SERVER (negotiates a modern version).",
      source="https://cwe.mitre.org/data/definitions/327.html",
      re=r"ssl\.PROTOCOL_(SSLv2|SSLv3|TLSv1)\b", nc="ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)",
      c="ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)"),
    r(id="python-jwt-verify-false", type="vuln", qual="sec", sev="high", cwe="CWE-347", owasp="A02:2021",
      title="JWT signature verification disabled", desc="jwt.decode(..., verify=False) accepts unsigned/forged tokens.",
      rationale="Skipping signature verification lets an attacker forge any claims.",
      remediation="Verify with the expected key and algorithms (verify_signature stays on).",
      source="https://cwe.mitre.org/data/definitions/347.html",
      re=r"jwt\.decode\s*\([^)]*verify\s*=\s*False", nc="payload = jwt.decode(token, verify=False)",
      c='payload = jwt.decode(token, key, algorithms=["HS256"])'),
]
