CC="commentOnlyLine"
def r(**k):
    k.setdefault("lang","java");k.setdefault("owasp","");k.setdefault("effort",15)
    k.setdefault("tags",["sast","java"]);k.setdefault("cat_desc",k["desc"]);k.setdefault("skip",CC)
    return k
RULES=[
 r(id="java-bigdecimal-double",type="bug",qual="rel",sev="medium",cwe="",title="BigDecimal from a double literal",
   desc="new BigDecimal(0.1) captures the double's rounding error.",
   rationale="Constructing BigDecimal from a double stores the exact (inexact) binary value, e.g. 0.1 becomes 0.1000000000000000055..., defeating the point of BigDecimal.",
   remediation="Use the String constructor: new BigDecimal(\"0.1\") (or BigDecimal.valueOf).",
   source="https://wiki.sei.cmu.edu/confluence/display/java/NUM10-J.+Do+not+construct+BigDecimal+objects+from+floating-point+literals",
   re=r"\bnew\s+BigDecimal\s*\(\s*[0-9]+\.[0-9]",nc="BigDecimal p = new BigDecimal(0.1);",c='BigDecimal p = new BigDecimal("0.1");'),
 r(id="java-boolean-literal-compare",type="smell",qual="maint",sev="low",cwe="",title="Comparison with a boolean literal",
   desc="`flag == true` is just `flag`.",
   rationale="Comparing a boolean to a literal is redundant and risks a stray = typo; use the boolean directly.",
   remediation="Use the boolean expression directly (or negate it).",
   source="https://pmd.github.io/pmd/pmd_rules_java_codestyle.html",
   re=r"==\s*(true|false)\b",nc="if (enabled == true) start();",c="if (enabled) start();"),
 r(id="java-system-out-print",type="smell",qual="maint",sev="low",cwe="",title="System.out/err print",
   desc="Printing to stdout/stderr bypasses the logging framework.",
   rationale="System.out/err writes escape the logging configuration, so output cannot be leveled, routed, or disabled in production.",
   remediation="Use the application logger.",
   source="https://pmd.github.io/pmd/pmd_rules_java_bestpractices.html",
   re=r"System\.(out|err)\.print",nc="System.out.println(result);",c="log.info(result);"),
 r(id="java-stringbuffer",type="smell",qual="maint",sev="low",cwe="",title="StringBuffer where StringBuilder fits",
   desc="StringBuffer synchronizes every call; StringBuilder is faster for local use.",
   rationale="StringBuffer's synchronization is pure overhead when the builder never crosses threads, which is the common case.",
   remediation="Use StringBuilder for non-shared string building.",
   source="https://docs.oracle.com/javase/8/docs/api/java/lang/StringBuilder.html",
   re=r"\bnew\s+StringBuffer\s*\(",nc="StringBuffer sb = new StringBuffer();",c="StringBuilder sb = new StringBuilder();"),
 r(id="java-date-int-ctor",type="bug",qual="rel",sev="low",cwe="",title="Deprecated Date(int,int,int) constructor",
   desc="new Date(year, month, day) is deprecated and uses 1900-based years.",
   rationale="The integer Date constructors are deprecated, interpret the year as offset-from-1900, and are error-prone; use java.time.",
   remediation="Use LocalDate.of(...) / java.time.",
   source="https://docs.oracle.com/javase/8/docs/api/java/util/Date.html",
   re=r"\bnew\s+Date\s*\(\s*[0-9]",nc="Date d = new Date(2020, 0, 1);",c="LocalDate d = LocalDate.of(2020, 1, 1);"),
 r(id="java-empty-finally",type="smell",qual="maint",sev="low",cwe="",title="Empty finally block",
   desc="An empty finally block is dead code.",
   rationale="A finally block that does nothing adds noise and may indicate forgotten cleanup.",
   remediation="Remove the empty finally, or add the intended cleanup.",
   source="https://pmd.github.io/pmd/pmd_rules_java_errorprone.html",
   re=r"finally\s*\{\s*\}",nc="} finally {}",c="} finally { in.close(); }"),
 r(id="java-throw-in-finally",type="bug",qual="rel",sev="medium",cwe="",title="throw inside a finally block",
   desc="Throwing in finally discards any exception from the try/catch.",
   rationale="A throw in finally replaces a pending exception, silently losing the original failure (SEI CERT ERR04-J).",
   remediation="Do not throw from finally; handle cleanup failures without masking the primary error.",
   source="https://wiki.sei.cmu.edu/confluence/display/java/ERR04-J.+Do+not+complete+abruptly+from+a+finally+block",
   re=r"finally\s*\{[^}]*\bthrow\b",nc="} finally { throw new IllegalStateException(); }",c="} finally { closeQuietly(in); }"),
 r(id="java-cond-assign",type="bug",qual="rel",sev="medium",cwe="",title="Assignment in a conditional (Java)",
   desc="An assignment inside an if/while condition is usually a mistaken ==.",
   rationale="An = inside a condition assigns and tests the result, almost always a typo for ==.",
   remediation="Use == (or move the assignment out of the condition).",
   source="https://pmd.github.io/pmd/pmd_rules_java_errorprone.html",
   re=r"\b(if|while)\s*\(\s*[A-Za-z_$][\w$.]*\s*=\s*[^=]",nc="if (line = reader.readLine()) {",c="while ((line = reader.readLine()) != null) {"),
 r(id="java-float-equality",type="bug",qual="rel",sev="medium",cwe="",title="Exact equality on a floating-point literal",
   desc="`x == 1.5` compares floating-point values exactly, which is unreliable.",
   rationale="Floating-point rounding means an equal-looking computation rarely equals the literal exactly; compare within a tolerance.",
   remediation="Compare with a small epsilon, e.g. Math.abs(x - 1.5) < EPS.",
   source="https://wiki.sei.cmu.edu/confluence/display/java/NUM04-J.+Do+not+use+floating-point+numbers+if+precise+computation+is+required",
   re=r"[=!]=\s*[0-9]+\.[0-9]+[fFdD]?",nc="if (rate == 1.5) apply();",c="if (Math.abs(rate - 1.5) < EPS) apply();"),
 r(id="java-enumeration",type="smell",qual="maint",sev="low",cwe="",title="Legacy Enumeration type",
   desc="Enumeration is the legacy iteration interface; use Iterator.",
   rationale="Enumeration predates the collections framework and lacks remove(); Iterator is the modern equivalent.",
   remediation="Use Iterator (or an enhanced for loop).",
   source="https://docs.oracle.com/javase/8/docs/api/java/util/Enumeration.html",
   re=r"\bEnumeration\s*<",nc="Enumeration<String> e = v.elements();",c="Iterator<String> it = list.iterator();"),
 r(id="java-toarray-noarg",type="smell",qual="maint",sev="low",cwe="",title="Collection.toArray() with no type",
   desc="toArray() returns Object[]; pass a typed array for a typed result.",
   rationale="The no-arg toArray returns Object[], forcing casts; the typed overload returns the right array type.",
   remediation="Use toArray(new T[0]).",
   source="https://errorprone.info/bugpattern/ToArrayCallWithZeroLengthArrayArgument",
   re=r"\.toArray\s*\(\s*\)",nc="Object[] a = items.toArray();",c="String[] a = items.toArray(new String[0]);"),
 r(id="java-catch-error",type="smell",qual="maint",sev="medium",cwe="",title="Catching java.lang.Error",
   desc="Catching Error traps JVM-level failures (OOM, stack overflow) that should propagate.",
   rationale="Errors indicate serious, usually unrecoverable JVM conditions; catching them can mask fatal problems and destabilize the process.",
   remediation="Catch specific recoverable exceptions, not Error.",
   source="https://wiki.sei.cmu.edu/confluence/display/java/ERR08-J.+Do+not+catch+NullPointerException+or+any+of+its+ancestors",
   re=r"catch\s*\(\s*Error\b",nc="try { compute(); } catch (Error e) { swallow(); }",c="try { compute(); } catch (ArithmeticException e) { recover(); }"),
 r(id="java-mutable-public-static-array",type="smell",qual="maint",sev="low",cwe="",title="Public static array field",
   desc="A public static array is mutable shared state, even when marked final.",
   rationale="Array contents stay writable through a public static (final) reference, so callers can mutate shared state.",
   remediation="Make it private and expose an unmodifiable copy or accessor.",
   source="https://wiki.sei.cmu.edu/confluence/display/java/OBJ01-J.+Limit+accessibility+of+fields",
   # A FIELD declaration: the array type is followed by a name and then "=" or ";". Without the
   # tail this also matched `public static int[] getCodes() {`, a method returning an array.
   re=r"\bpublic\s+static\s+(?:final\s+)?[\w.<>]+\s*\[\s*\]\s+[A-Za-z_]\w*\s*(?:=|;)",
   nc="public static int[] CODES = {1, 2};",
   c="private static final List<Integer> CODES = List.of(1, 2);\npublic static int[] getCodes() { return CODES.clone(); }"),
 r(id="java-string-equals-empty",type="smell",qual="maint",sev="low",cwe="",title="equals(\"\") instead of isEmpty()",
   desc="`s.equals(\"\")` is clearer as `s.isEmpty()`.",
   rationale="isEmpty() states intent directly and avoids allocating/scanning against an empty literal.",
   remediation="Use s.isEmpty().",
   source="https://pmd.github.io/pmd/pmd_rules_java_performance.html",
   re=r'\.equals\s*\(\s*""\s*\)',nc='if (name.equals("")) return;',c="if (name.isEmpty()) return;"),
]
