CC = "commentOnlyLine"


def r(**k):
    k.setdefault("lang", "py")
    k.setdefault("owasp", "")
    k.setdefault("effort", 15)
    k.setdefault("tags", ["sast", "python"])
    k.setdefault("cat_desc", k["desc"])
    k.setdefault("skip", CC)
    return k


# Python quality pack, batch 9: comprehensions, pyupgrade idioms, deprecated/removed stdlib modules.
RULES = [
    r(id="python-unnecessary-dict-kwargs", type="smell", qual="maint", sev="low", cwe="",
      title="**{...} literal as kwargs", desc="Unpacking a dict literal into kwargs is just passing keyword args.",
      rationale="func(**{\"a\": 1}) is more clearly written func(a=1) (flake8-pie PIE804).",
      remediation="Pass keyword arguments directly.",
      source="https://github.com/sbdchd/flake8-pie",
      re=r"\*\*\{", nc='build(**{"host": h})', c="build(host=h)"),
    r(id="python-list-generator-comprehension", type="smell", qual="maint", sev="low", cwe="",
      title="list() over a generator expression", desc="list(x for x in y) is a list comprehension.",
      rationale="Passing a generator to list() is clearer as a list comprehension (flake8-comprehensions C400).",
      remediation="Use a list comprehension: [x for x in y].",
      source="https://github.com/adamchainz/flake8-comprehensions",
      re=r"\blist\s*\(\s*\w+\s+for\s", nc="nums = list(x for x in items)", c="nums = [x for x in items]"),
    r(id="python-set-generator-comprehension", type="smell", qual="maint", sev="low", cwe="",
      title="set() over a generator expression", desc="set(x for x in y) is a set comprehension.",
      rationale="Passing a generator to set() is clearer as a set comprehension (flake8-comprehensions C401).",
      remediation="Use a set comprehension: {x for x in y}.",
      source="https://github.com/adamchainz/flake8-comprehensions",
      re=r"\bset\s*\(\s*\w+\s+for\s", nc="uniq = set(x for x in items)", c="uniq = {x for x in items}"),
    r(id="python-unnecessary-encode-utf8", type="smell", qual="maint", sev="low", cwe="",
      title="Redundant encode(\"utf-8\")", desc="UTF-8 is the default encoding for str.encode.",
      rationale="str.encode() already uses UTF-8, so the explicit argument is redundant (pyupgrade UP012).",
      remediation="Call encode() with no argument.",
      source="https://github.com/asottile/pyupgrade",
      re=r'''\.encode\s*\(\s*["']utf-?8["']\s*\)''', nc='data = text.encode("utf-8")', c="data = text.encode()"),
    r(id="python-redundant-open-mode-r", type="smell", qual="maint", sev="low", cwe="",
      title="Redundant open mode \"r\"", desc="\"r\" is the default file mode.",
      rationale="open(path, \"r\") is the same as open(path) (pyupgrade UP015).",
      remediation="Drop the explicit \"r\" mode.",
      source="https://github.com/asottile/pyupgrade",
      re=r'''\bopen\s*\([^,)]+,\s*["']r["']\s*\)''', nc='f = open(path, "r")', c="f = open(path)"),
    r(id="python-os-error-alias", type="smell", qual="maint", sev="low", cwe="",
      title="Deprecated OSError alias", desc="IOError/EnvironmentError/WindowsError are aliases of OSError.",
      rationale="These aliases are legacy; OSError is the canonical name since Python 3.3 (pyupgrade UP024).",
      remediation="Use OSError.",
      source="https://docs.python.org/3/library/exceptions.html#OSError",
      re=r"\b(IOError|EnvironmentError|WindowsError)\b", nc="except IOError:", c="except OSError:"),
    r(id="python-deprecated-unittest-assert", type="smell", qual="maint", sev="low", cwe="",
      title="Deprecated unittest assert alias", desc="assertEquals/assert_/failUnless are deprecated aliases.",
      rationale="These camel/legacy assert aliases are deprecated in favor of assertEqual etc (pyupgrade UP005).",
      remediation="Use the canonical name, e.g. assertEqual.",
      source="https://docs.python.org/3/library/unittest.html#deprecated-aliases",
      re=r"\.(assertEquals|assertNotEquals|assertItemsEqual|assert_|failUnless|failIf|failUnlessEqual)\b",
      nc="self.assertEquals(a, b)", c="self.assertEqual(a, b)"),
    r(id="python-logging-warn", type="smell", qual="maint", sev="low", cwe="",
      title="Deprecated logger.warn()", desc="Logger.warn is deprecated in favor of warning.",
      rationale="logging.warn / logger.warn have been deprecated since Python 3.3.",
      remediation="Use logger.warning(...).",
      source="https://docs.python.org/3/library/logging.html#logging.Logger.warning",
      re=r"\b(logger|logging|log)\.warn\s*\(", nc='logger.warn("slow")', c='logger.warning("slow")'),
    r(id="python-readlines-in-loop", type="smell", qual="maint", sev="low", cwe="",
      title="Iterating file.readlines()", desc="Iterating readlines() loads the whole file into memory.",
      rationale="A file object is already an iterator of lines, so readlines() wastes memory (refurb FURB129).",
      remediation="Iterate the file directly: for line in f.",
      source="https://github.com/dosisod/refurb",
      re=r"\.readlines\s*\(\s*\)", nc="for line in f.readlines():", c="for line in f:"),
    r(id="python-assert-string-literal", type="bug", qual="rel", sev="medium", cwe="",
      title="assert on a string literal", desc="assert \"msg\" is always true (a non-empty string is truthy).",
      rationale="Asserting a string literal never fails; the message was likely meant as the second argument.",
      remediation="Assert the condition and pass the message: assert cond, \"msg\".",
      source="https://github.com/PyCQA/flake8-bugbear",
      # The WHOLE condition has to be the literal, optionally followed by the assert message or a
      # trailing comment. Matching a leading quote alone fired on every `assert "x" in y`,
      # `assert \'a\' == b`, `assert "%s" % v` and `assert "".join(y)`, which are ordinary conditions.
      re=r'''\bassert\s+(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')\s*(?:,[^\n]*)?(?:#[^\n]*)?\s*$''',
      nc='assert "must be configured"',
      c='assert value, "must be configured"\nassert "X" in y\nassert \'a\' == b\nassert "%s" % v\nassert "".join(y)\nassert name.startswith("x")'),
    r(id="python-range-start-zero", type="smell", qual="maint", sev="low", cwe="",
      title="range(0, n)", desc="range(0, n) is just range(n).",
      rationale="The start defaults to 0, so range(0, n) is redundant (flake8-pie PIE808).",
      remediation="Use range(n).",
      source="https://github.com/sbdchd/flake8-pie",
      re=r"range\s*\(\s*0\s*,", nc="for i in range(0, n):", c="for i in range(n):"),
    r(id="python-future-import-py2", type="smell", qual="maint", sev="low", cwe="",
      title="Python 2 __future__ import", desc="These __future__ features are always on in Python 3.",
      rationale="print_function/unicode_literals/division etc are no-ops in Python 3 (pyupgrade UP010).",
      remediation="Remove the redundant __future__ import.",
      source="https://github.com/asottile/pyupgrade",
      re=r"from\s+__future__\s+import\s+(print_function|unicode_literals|division|absolute_import|generators|nested_scopes|with_statement|generator_stop)",
      nc="from __future__ import unicode_literals", c="from __future__ import annotations"),
    r(id="python-mock-import", type="smell", qual="maint", sev="low", cwe="",
      title="Third-party mock import", desc="mock is part of the standard library as unittest.mock.",
      rationale="The standalone mock backport is unnecessary on Python 3 (pyupgrade UP026).",
      remediation="Use from unittest import mock.",
      source="https://github.com/asottile/pyupgrade",
      re=r"^\s*import\s+mock\b", nc="import mock", c="from unittest import mock"),
    r(id="python-six-import", type="smell", qual="maint", sev="low", cwe="",
      title="six compatibility import", desc="six exists only to bridge Python 2 and 3.",
      rationale="On a Python 3-only codebase, six is dead weight.",
      remediation="Remove six and use the Python 3 API directly.",
      source="https://github.com/asottile/pyupgrade",
      re=r"^\s*(import\s+six|from\s+six\b)", nc="import six", c="import functools"),
    r(id="python-optparse-import", type="smell", qual="maint", sev="low", cwe="",
      title="Deprecated optparse module", desc="optparse is deprecated in favor of argparse.",
      rationale="optparse has been deprecated since Python 3.2.",
      remediation="Use argparse.",
      source="https://docs.python.org/3/library/optparse.html",
      re=r"\b(import\s+optparse|from\s+optparse\b)", nc="import optparse", c="import argparse"),
    r(id="python-cgi-import", type="bug", qual="rel", sev="medium", cwe="",
      title="Removed cgi module", desc="The cgi module was removed in Python 3.13.",
      rationale="import cgi raises ModuleNotFoundError on Python 3.13+.",
      remediation="Use email.message / urllib.parse / a web framework instead.",
      source="https://docs.python.org/3/whatsnew/3.13.html",
      re=r"^\s*(import\s+cgi|from\s+cgi\b)", nc="import cgi", c="from urllib.parse import parse_qs"),
    r(id="python-asyncore-import", type="bug", qual="rel", sev="medium", cwe="",
      title="Removed asyncore module", desc="The asyncore module was removed in Python 3.12.",
      rationale="import asyncore raises ModuleNotFoundError on Python 3.12+.",
      remediation="Use the asyncio module.",
      source="https://docs.python.org/3/whatsnew/3.12.html",
      re=r"\b(import\s+asyncore|from\s+asyncore\b)", nc="import asyncore", c="import asyncio"),
    r(id="python-distutils-import", type="bug", qual="rel", sev="medium", cwe="",
      title="Removed distutils module", desc="The distutils module was removed in Python 3.12.",
      rationale="importing distutils raises ModuleNotFoundError on Python 3.12+.",
      remediation="Use setuptools or packaging.",
      source="https://docs.python.org/3/whatsnew/3.12.html",
      re=r"\b(import\s+distutils|from\s+distutils\b)", nc="from distutils.core import setup", c="from setuptools import setup"),
]
