package rulecatalog

import (
	"github.com/KKloudTarus/synapse-ce/internal/domain/rule"
	"github.com/KKloudTarus/synapse-ce/internal/domain/shared"
)

func sastRules() []rule.Rule {
	return []rule.Rule{
		{
			Key:                 "weak-hash-md5",
			Name:                "Weak hash: MD5",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"sast", "weak-crypto", "md5"},
			CWE:                 []string{"CWE-327"},
			OWASP:               []string{"A02:2021"},
			Description:         "MD5 is cryptographically broken and vulnerable to collision attacks.",
			Rationale:           "MD5 produces a 128-bit hash value that can be cracked rapidly on modern hardware. It is no longer considered secure for any cryptographic purpose, including digital signatures, file integrity checks, or password hashing.\n\nSource: https://cwe.mitre.org/data/definitions/327.html",
			Remediation:         "Replace MD5 with a secure hashing algorithm like SHA-256 or SHA-3 for general hashing, or use a key derivation function like Argon2id for passwords.",
			CompliantExample:    "h := sha256.New()\nh.Write(data)",
			NoncompliantExample: "h := md5.New()\nh.Write(data)",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "weak-hash-sha1",
			Name:                "Weak hash: SHA-1",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"sast", "weak-crypto", "sha1"},
			CWE:                 []string{"CWE-327"},
			OWASP:               []string{"A02:2021"},
			Description:         "SHA-1 is collision-vulnerable and deprecated for cryptographic use.",
			Rationale:           "SHA-1 has been proven to be vulnerable to collision attacks, meaning two different inputs can produce the same hash. This breaks the integrity guarantees required for digital signatures and certificates.\n\nSource: https://cwe.mitre.org/data/definitions/327.html",
			Remediation:         "Migrate all hashing operations that rely on SHA-1 to a stronger algorithm belonging to the SHA-2 or SHA-3 family, such as SHA-256.",
			CompliantExample:    "h := sha256.New()\nh.Write(data)",
			NoncompliantExample: "h := sha1.New()\nh.Write(data)",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "weak-cipher",
			Name:                "Weak cipher: DES/3DES/RC4",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "weak-crypto", "cipher"},
			CWE:                 []string{"CWE-327"},
			OWASP:               []string{"A02:2021"},
			Description:         "DES, 3DES, and RC4 are weak encryption algorithms vulnerable to practical attacks.",
			Rationale:           "Legacy ciphers like DES have a small key size (56 bits) that can be brute-forced. RC4 has inherent biases in its keystream. Using them compromises the confidentiality of encrypted data.\n\nSource: https://cwe.mitre.org/data/definitions/327.html",
			Remediation:         "Replace legacy ciphers with a modern, authenticated encryption algorithm such as AES-GCM or ChaCha20-Poly1305.",
			CompliantExample:    "Cipher.getInstance(\"AES/GCM/NoPadding\")",
			NoncompliantExample: "Cipher.getInstance(\"DES\")",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "insecure-tls-verify-disabled",
			Name:                "TLS certificate verification disabled",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "insecure-tls", "network"},
			CWE:                 []string{"CWE-295"},
			OWASP:               []string{"A07:2021"},
			Description:         "Disabling TLS certificate verification enables machine-in-the-middle attacks.",
			Rationale:           "Setting InsecureSkipVerify to true instructs the TLS client to accept any certificate presented by the server, regardless of hostname mismatches or untrusted certificate authorities, completely defeating the purpose of TLS encryption.\n\nSource: https://cwe.mitre.org/data/definitions/295.html",
			Remediation:         "Ensure InsecureSkipVerify is set to false in production code. If communicating with internal services, add the internal CA to the trusted root pool instead of disabling verification.",
			CompliantExample:    "tlsConfig := &tls.Config{InsecureSkipVerify: false}",
			NoncompliantExample: "tlsConfig := &tls.Config{InsecureSkipVerify: true}",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "debug-mode-enabled",
			Name:                "Active debug mode enabled",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"sast", "debug", "configuration"},
			CWE:                 []string{"CWE-489"},
			OWASP:               []string{"A05:2021"},
			Description:         "Debug mode exposes internal application details and verbose errors.",
			Rationale:           "Leaving debug features enabled in a production environment can leak stack traces, environment variables, and internal architecture details to an attacker, facilitating further exploitation.\n\nSource: https://cwe.mitre.org/data/definitions/489.html",
			Remediation:         "Disable framework debug modes or verbose error reporting by default. Control the debug state strictly through environment variables that are set to false in production.",
			CompliantExample:    "app.run(debug=False)",
			NoncompliantExample: "app.run(debug=True)",
			RemediationEffort:   5,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "permissive-cors-wildcard",
			Name:                "Permissive CORS: wildcard origin",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"sast", "cors", "network"},
			CWE:                 []string{"CWE-942"},
			OWASP:               []string{"A05:2021"},
			Description:         "CORS allows any origin ('*'), enabling cross-origin attacks.",
			Rationale:           "A wildcard CORS policy allows any website to make authenticated requests to the API on behalf of the user, potentially exposing sensitive data or allowing unauthorized state changes via Cross-Origin Resource Sharing.\n\nSource: https://cwe.mitre.org/data/definitions/942.html",
			Remediation:         "Configure the CORS middleware to only accept origins from explicitly trusted domains. Avoid dynamically reflecting the Origin header without strict validation.",
			CompliantExample:    "cors.New(cors.Options{AllowedOrigins: []string{\"https://trusted.com\"}})",
			NoncompliantExample: "cors.New(cors.Options{AllowedOrigins: []string{\"*\"}})",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "hardcoded-aws-access-key",
			Name:                "Hardcoded AWS access key id",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityCritical,
			Tags:                []string{"sast", "hardcoded-secret", "aws"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "An AWS access key ID is hardcoded in the source code.",
			Rationale:           "Embedding AWS credentials directly in source code allows anyone with access to the repository to impersonate the IAM user and potentially compromise the cloud infrastructure.\n\nSource: https://cwe.mitre.org/data/definitions/798.html",
			Remediation:         "Remove the hardcoded credential, rotate it immediately in the AWS console, and use IAM roles or environment variables (e.g., AWS_ACCESS_KEY_ID) to provide credentials dynamically.",
			CompliantExample:    "keyID := os.Getenv(\"AWS_ACCESS_KEY_ID\")",
			NoncompliantExample: "keyID := \"AKIAIOSFODNN7EXAMPLE\"",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "private-key-material",
			Name:                "Private key material in source",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityCritical,
			Tags:                []string{"sast", "hardcoded-secret", "crypto"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "A PEM-encoded private key block is embedded in the source code.",
			Rationale:           "Hardcoded private keys compromise the confidentiality and integrity of any cryptographic operations that rely on them. Once checked into version control, the key is permanently compromised.\n\nSource: https://cwe.mitre.org/data/definitions/798.html",
			Remediation:         "Rotate the compromised key immediately. Load the new private key securely from a keystore, a secrets manager, or an environment variable at runtime.",
			CompliantExample:    "keyData, err := os.ReadFile(\"/path/to/secret/key.pem\")",
			NoncompliantExample: "keyData := \"-----BEGIN PRIVATE KEY-----\\nMIIC...\"",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "hardcoded-credential",
			Name:                "Possible hardcoded credential",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "hardcoded-secret", "password"},
			CWE:                 []string{"CWE-798"},
			OWASP:               []string{"A07:2021"},
			Description:         "A variable appearing to hold a credential is assigned a literal secret value.",
			Rationale:           "Storing passwords or tokens in plaintext within the source code makes it trivial for an attacker or malicious insider who gains source access to move laterally into authenticated systems.\n\nSource: https://cwe.mitre.org/data/definitions/798.html",
			Remediation:         "Remove the literal string. Supply the credential via environment variables or a dedicated secrets manager.",
			CompliantExample:    "password = os.getenv(\"DB_PASSWORD\")",
			NoncompliantExample: "password = \"my_super_secret_password_123\"",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "password-md5-hash",
			Name:                "Password hashed with unsalted MD5",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"sast", "crypto", "password"},
			CWE:                 []string{"CWE-916"},
			OWASP:               []string{"A02:2021"},
			Description:         "MD5 is extremely fast and unsalted, making it completely inadequate for password hashing.",
			Rationale:           "Fast hash functions like MD5 allow attackers to calculate billions of hashes per second. Without a salt and adaptive work factor, password databases hashed with MD5 are trivially cracked using rainbow tables or brute force.\n\nSource: https://cwe.mitre.org/data/definitions/916.html",
			Remediation:         "Switch to a modern, adaptive, salted key derivation function designed for passwords, such as Argon2id, bcrypt, or scrypt.",
			CompliantExample:    "hash = bcrypt.hashpw(password, bcrypt.gensalt())",
			NoncompliantExample: "hash = hashlib.md5(password).hexdigest()",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "prisma-raw-sql-unsafe",
			Name:                "Raw SQL query uses unsafe Prisma API",
			Language:            "JavaScript/TypeScript",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityCritical,
			Tags:                []string{"sast", "sql-injection", "prisma"},
			CWE:                 []string{"CWE-89"},
			OWASP:               []string{"A03:2021"},
			Description:         "Prisma's $queryRawUnsafe executes dynamically constructed SQL without parameterization.",
			Rationale:           "Using $queryRawUnsafe with string concatenation or interpolation allows attackers to alter the structure of the SQL query, leading to SQL injection which can compromise the entire database.\n\nSource: https://cwe.mitre.org/data/definitions/89.html",
			Remediation:         "Replace $queryRawUnsafe with $queryRaw which uses tagged template literals for automatic parameterization, or use the standard Prisma ORM methods.",
			CompliantExample:    "prisma.$queryRaw`SELECT * FROM User WHERE id = ${id}`",
			NoncompliantExample: "prisma.$queryRawUnsafe(`SELECT * FROM User WHERE id = ${id}`)",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "template-sql-interpolation",
			Name:                "SQL string interpolates dynamic data",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityCritical,
			Tags:                []string{"sast", "sql-injection", "template"},
			CWE:                 []string{"CWE-89"},
			OWASP:               []string{"A03:2021"},
			Description:         "A SQL string is built using template interpolation instead of parameterized variables.",
			Rationale:           "String interpolation directly embeds untrusted values into the SQL command text. This bypasses the database driver's protection mechanisms, allowing attackers to inject arbitrary SQL logic.\n\nSource: https://cwe.mitre.org/data/definitions/89.html",
			Remediation:         "Use standard parameterized queries (e.g., using ? or $1) provided by the database driver to bind variables securely.",
			CompliantExample:    "db.query(\"SELECT * FROM users WHERE id = $1\", [userId])",
			NoncompliantExample: "db.query(`SELECT * FROM users WHERE id = ${userId}`)",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "generic-sql-dynamic-execute",
			Name:                "SQL execution uses dynamic string construction",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "sql-injection"},
			CWE:                 []string{"CWE-89"},
			OWASP:               []string{"A03:2021"},
			Description:         "A generic database execution sink receives a dynamically concatenated string.",
			Rationale:           "Dynamically concatenating strings to form database queries is the root cause of SQL injection. The execution sink cannot distinguish between the query structure and the untrusted payload.\n\nSource: https://cwe.mitre.org/data/definitions/89.html",
			Remediation:         "Rewrite the query to use the appropriate parameter binding syntax for the target database.",
			CompliantExample:    "db.execute(\"SELECT * FROM users WHERE id = ?\", (user_id,))",
			NoncompliantExample: "db.execute(\"SELECT * FROM users WHERE id = \" + user_id)",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "go-sql-dynamic-query",
			Name:                "Go SQL query uses dynamic string construction",
			Language:            "Go",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "sql-injection", "go"},
			CWE:                 []string{"CWE-89"},
			OWASP:               []string{"A03:2021"},
			Description:         "The database/sql package is called with a query built using string concatenation.",
			Rationale:           "Passing concatenated strings to Query() or QueryRow() opens the application to SQL injection, permitting an attacker to read or modify arbitrary data.\n\nSource: https://cwe.mitre.org/data/definitions/89.html",
			Remediation:         "Use placeholder parameters (? or $1) and pass the variables as subsequent arguments to the Query method.",
			CompliantExample:    "rows, err := db.Query(\"SELECT email FROM users WHERE username=?\", user)",
			NoncompliantExample: "rows, err := db.Query(\"SELECT email FROM users WHERE username='\" + user + \"'\")",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "sqlalchemy-raw-sql-dynamic",
			Name:                "Python SQLAlchemy/raw SQL uses dynamic string construction",
			Language:            "Python",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "sql-injection", "python"},
			CWE:                 []string{"CWE-89"},
			OWASP:               []string{"A03:2021"},
			Description:         "SQLAlchemy's text() or raw execute() is used with Python string formatting (f-strings).",
			Rationale:           "Using f-strings or the .format() method to build SQL queries bypasses SQLAlchemy's parameter binding, directly exposing the application to SQL injection vulnerabilities.\n\nSource: https://cwe.mitre.org/data/definitions/89.html",
			Remediation:         "Use SQLAlchemy's text() function with bind parameters, passing a dictionary of variables to the execute() method.",
			CompliantExample:    "session.execute(text(\"SELECT * FROM users WHERE id = :id\"), {'id': user_id})",
			NoncompliantExample: "session.execute(f\"SELECT * FROM users WHERE id = {user_id}\")",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "child-process-exec-template",
			Name:                "Shell command uses template interpolation",
			Language:            "JavaScript/TypeScript",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityCritical,
			Tags:                []string{"sast", "command-injection", "node"},
			CWE:                 []string{"CWE-78"},
			OWASP:               []string{"A03:2021"},
			Description:         "child_process.exec() is called with a command string built using template literals.",
			Rationale:           "The exec() function invokes a shell. Interpolating variables directly into the command string allows an attacker to append malicious shell operators (like && or |) to execute arbitrary commands.\n\nSource: https://cwe.mitre.org/data/definitions/78.html",
			Remediation:         "Use child_process.execFile() or spawn() which bypass the shell entirely by taking arguments as an explicit array.",
			CompliantExample:    "execFile('ls', ['-l', dirPath], callback)",
			NoncompliantExample: "exec(`ls -l ${dirPath}`, callback)",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "generic-command-injection-sink",
			Name:                "Command execution sink receives dynamic input",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "command-injection"},
			CWE:                 []string{"CWE-78"},
			OWASP:               []string{"A03:2021"},
			Description:         "A system command execution sink evaluates a dynamically constructed string.",
			Rationale:           "Building shell commands via string concatenation makes it trivial for an attacker to break out of the intended command context and execute arbitrary binaries on the host system.\n\nSource: https://cwe.mitre.org/data/definitions/78.html",
			Remediation:         "Avoid shell invocation. Pass arguments as separate array elements to the execution API, and rigorously validate the input against an allowlist.",
			CompliantExample:    "subprocess.run([\"ls\", \"-l\"])",
			NoncompliantExample: "os.system(\"rm -rf \" + request.GET['dir'])",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "go-command-dynamic",
			Name:                "Go command execution receives dynamic input",
			Language:            "Go",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "command-injection", "go"},
			CWE:                 []string{"CWE-78"},
			OWASP:               []string{"A03:2021"},
			Description:         "The os/exec package is used with dynamically constructed arguments that may include a shell.",
			Rationale:           "When os/exec is used to run a shell (sh -c or cmd.exe /c), passing concatenated strings as the shell payload creates a direct command injection vector.\n\nSource: https://cwe.mitre.org/data/definitions/78.html",
			Remediation:         "Execute the target binary directly without a shell interpreter, passing untrusted inputs as subsequent string arguments in the exec.Command call.",
			CompliantExample:    "exec.Command(\"1\")",
			NoncompliantExample: "exec.Command(c.Query(\"cmd\"))",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "go-subprocess-untrusted-arg",
			Name:                "Untrusted value passed as a subprocess argument",
			Language:            "Go",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"sast", "argument-injection", "go"},
			CWE:                 []string{"CWE-88"},
			OWASP:               []string{"A03:2021"},
			Description:         "A request-derived value reaches an os/exec argument. The program is spawned directly with an argv array, so no shell re-parses the value.",
			Rationale:           "Without a shell there is no command injection, which is why exec.Command with a constant program is the recommended way to pass untrusted input. The residual risk is argument injection: the callee may read a value beginning with a dash as an option, or treat it as a path.\n\nSource: https://cwe.mitre.org/data/definitions/88.html",
			Remediation:         "Validate the value against an allowlist, and pass `--` before positional arguments so the callee cannot read it as an option.",
			CompliantExample:    "exec.Command(\"ping\", \"-c\", \"1\", \"--\", allowlisted(host))",
			NoncompliantExample: "exec.Command(\"ping\", \"-c\", \"1\", c.Query(\"host\"))",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "unsafe-deserialization-node-serialize",
			Name:                "Unsafe node-serialize deserialization",
			Language:            "JavaScript/TypeScript",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "deserialization", "node"},
			CWE:                 []string{"CWE-502"},
			OWASP:               []string{"A08:2021"},
			Description:         "The node-serialize package is used to deserialize data.",
			Rationale:           "The node-serialize package supports an Immediately Invoked Function Expression (IIFE) payload during unserialization. An attacker can provide crafted JSON that executes arbitrary JavaScript upon parsing.\n\nSource: https://cwe.mitre.org/data/definitions/502.html",
			Remediation:         "Remove the node-serialize package. Use standard JSON.parse() and validate the structure of the incoming data.",
			CompliantExample:    "const obj = JSON.parse(userInput)",
			NoncompliantExample: "const obj = serialize.unserialize(userInput)",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "unsafe-deserialization-generic",
			Name:                "Unsafe deserialization of potentially untrusted data",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "deserialization"},
			CWE:                 []string{"CWE-502"},
			OWASP:               []string{"A08:2021"},
			Description:         "An unsafe deserialization function (e.g., gob.Decode with interface types) is used on untrusted data.",
			Rationale:           "Deserializing untrusted data without type strictness allows an attacker to dictate the classes or structures instantiated in memory, potentially triggering malicious side effects or RCE during garbage collection or method invocation.\n\nSource: https://cwe.mitre.org/data/definitions/502.html",
			Remediation:         "Use safe, data-only formats like JSON. If complex deserialization is required, implement strict typing, type whitelists, or cryptographic signatures before deserializing.",
			CompliantExample:    "json.loads(data)",
			NoncompliantExample: "pickle.loads(data)",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "ssrf-fetch-user-url",
			Name:                "Server-side fetch of user-controlled URL",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "ssrf"},
			CWE:                 []string{"CWE-918"},
			OWASP:               []string{"A01:2021"},
			Description:         "The application initiates an HTTP fetch based on a dynamically supplied URL string.",
			Rationale:           "Permitting users to control the destination of server-side HTTP requests can allow Server-Side Request Forgery (SSRF). Attackers can scan internal networks, access cloud metadata services (e.g., AWS IMDS), or bypass firewalls.\n\nSource: https://cwe.mitre.org/data/definitions/918.html",
			Remediation:         "Validate the target URL against a strict whitelist of permitted hosts. Prevent resolution of internal IP addresses and do not follow untrusted redirects.",
			CompliantExample:    "fetch(\"https://api.example.com/data\")",
			NoncompliantExample: "fetch(req.query.url)",
			RemediationEffort:   60,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "generic-ssrf-request-url",
			Name:                "Server-side request uses request-controlled URL",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "ssrf"},
			CWE:                 []string{"CWE-918"},
			OWASP:               []string{"A01:2021"},
			Description:         "A generic outbound network request reads its destination directly from incoming input.",
			Rationale:           "If the destination URL is not strictly validated, an attacker can coerce the server into acting as a proxy to attack other infrastructure behind the corporate firewall.\n\nSource: https://cwe.mitre.org/data/definitions/918.html",
			Remediation:         "Implement a dedicated SSRF protection proxy or network egress filtering. At the application layer, parse the URL and enforce domain allowlists.",
			CompliantExample:    "http.get(\"https://api.example.com/data\")",
			NoncompliantExample: "http.get(req.query.url)",
			RemediationEffort:   60,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "go-ssrf-dynamic-url",
			Name:                "Go server-side request uses dynamic URL",
			Language:            "Go",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "ssrf", "go"},
			CWE:                 []string{"CWE-918"},
			OWASP:               []string{"A01:2021"},
			Description:         "Go's net/http package is used to fetch a dynamically constructed URL.",
			Rationale:           "Without proper validation, Go's HTTP client will faithfully connect to internal IP blocks (e.g., 169.254.169.254) or internal services if the input specifies them, leading to severe information disclosure.\n\nSource: https://cwe.mitre.org/data/definitions/918.html",
			Remediation:         "Parse the input with net/url. Resolve the DNS record and assert that the resulting IP is public and not reserved for local networking before performing the fetch.",
			CompliantExample:    "http.Get(\"https://trusted.com\")",
			NoncompliantExample: "http.Get(userURL)",
			RemediationEffort:   60,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "react-dangerous-html",
			Name:                "React renders unsanitized HTML",
			Language:            "JavaScript/TypeScript",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "xss", "react"},
			CWE:                 []string{"CWE-79"},
			OWASP:               []string{"A03:2021"},
			Description:         "React's dangerouslySetInnerHTML is used to render DOM content.",
			Rationale:           "Using dangerouslySetInnerHTML circumvents React's built-in XSS protection (which normally escapes text). If the input is not rigorously sanitized, it introduces a Cross-Site Scripting (XSS) vulnerability.\n\nSource: https://cwe.mitre.org/data/definitions/79.html",
			Remediation:         "Avoid dangerouslySetInnerHTML. If HTML must be rendered, process the input through a robust sanitizer library (like DOMPurify) before passing it to React.",
			CompliantExample:    "<div className=\"user-content\">{userHtml}</div>",
			NoncompliantExample: "<div dangerouslySetInnerHTML={{ __html: userHtml }} />",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "reflected-response-write",
			Name:                "Response writes potentially unescaped request data",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "xss"},
			CWE:                 []string{"CWE-79"},
			OWASP:               []string{"A03:2021"},
			Description:         "An HTTP response writer emits request-controlled data directly.",
			Rationale:           "Writing unescaped request parameters back to the HTTP response can allow an attacker to inject malicious scripts into the victim's browser, leading to Reflected XSS.\n\nSource: https://cwe.mitre.org/data/definitions/79.html",
			Remediation:         "Use a templating engine with automatic contextual escaping (e.g., html/template), or explicitly escape strings using html.EscapeString before writing them to the response body.",
			CompliantExample:    "res.send(\"1\")",
			NoncompliantExample: "res.send(req.query.name)",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "server-template-injection",
			Name:                "Template rendering uses dynamic template text",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "ssti", "template"},
			CWE:                 []string{"CWE-1336"},
			OWASP:               []string{"A03:2021"},
			Description:         "A server-side template engine parses untrusted template source code.",
			Rationale:           "If an attacker can control the structure of the template itself (rather than just the data variables), they can exploit template language features to achieve Remote Code Execution (Server-Side Template Injection).\n\nSource: https://cwe.mitre.org/data/definitions/1336.html",
			Remediation:         "Never construct template definitions dynamically from user input. Pre-compile static templates and only pass user data into the template execution context as variables.",
			CompliantExample:    "render_template(\"index.html\", name=request.args.get('name'))",
			NoncompliantExample: "render_template_string(\"Hello \" + request.args.get('name'))",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "password-reset-token-disclosure",
			Name:                "Password reset token may be disclosed",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityCritical,
			Tags:                []string{"sast", "disclosure", "authentication"},
			CWE:                 []string{"CWE-640"},
			OWASP:               []string{"A07:2021"},
			Description:         "A password reset token is being logged or returned in an API response.",
			Rationale:           "Exposing a password reset token through any channel other than the intended out-of-band delivery mechanism (like an email to the user) allows an attacker to intercept the token and hijack the user's account.\n\nSource: https://cwe.mitre.org/data/definitions/640.html",
			Remediation:         "Send the token directly to the user's email or SMS. Never log the plaintext token or include it in the HTTP response payload.",
			CompliantExample:    "console.log(\"Password reset email sent to user\")",
			NoncompliantExample: "console.log(\"Token: \" + resetUrl)",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "sensitive-data-logging",
			Name:                "Sensitive data written to logs",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"sast", "logging", "privacy"},
			CWE:                 []string{"CWE-532"},
			OWASP:               []string{"A09:2021"},
			Description:         "Passwords, API keys, or personally identifiable information (PII) are being written to application logs.",
			Rationale:           "Log aggregators are rarely secured to the same level as the application database. Logging sensitive data creates a secondary exposure risk if the log management system is compromised or overly accessible to staff.\n\nSource: https://cwe.mitre.org/data/definitions/532.html",
			Remediation:         "Implement automated redaction or masking in the logging framework for known sensitive fields. Explicitly omit passwords and session tokens from debug statements.",
			CompliantExample:    "console.log(\"User logged in\")",
			NoncompliantExample: "console.log(\"User password is \" + password)",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "insecure-cookie-flags",
			Name:                "Session cookie uses insecure flags",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"sast", "cookie", "session"},
			CWE:                 []string{"CWE-614"},
			OWASP:               []string{"A05:2021"},
			Description:         "A session cookie is created without the Secure or HttpOnly flags.",
			Rationale:           "Without the HttpOnly flag, cookies can be stolen via XSS. Without the Secure flag, cookies can be intercepted in plaintext over unencrypted HTTP connections on the local network.\n\nSource: https://cwe.mitre.org/data/definitions/614.html",
			Remediation:         "Ensure all session and authentication cookies explicitly set Secure: true, HttpOnly: true, and apply an appropriate SameSite policy (Lax or Strict).",
			CompliantExample:    "res.cookie('session', '123', { secure: true, httpOnly: true })",
			NoncompliantExample: "res.cookie('session', '123', { secure: false })",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "jwt-hardcoded-secret-or-none",
			Name:                "JWT uses hardcoded secret or insecure algorithm",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "jwt", "crypto"},
			CWE:                 []string{"CWE-347"},
			OWASP:               []string{"A02:2021"},
			Description:         "JWT validation accepts the 'none' algorithm or relies on a hardcoded, guessable signing secret.",
			Rationale:           "If the 'none' algorithm is permitted, an attacker can construct a valid token bypassing signature checks. A hardcoded secret allows offline token forgery by anyone with access to the source code.\n\nSource: https://cwe.mitre.org/data/definitions/347.html",
			Remediation:         "Configure the JWT library to strictly enforce expected algorithms (e.g., RS256). Load the secret signing key dynamically from an environment variable or vault.",
			CompliantExample:    "jwt.sign(payload, process.env.JWT_SECRET)",
			NoncompliantExample: "jwt.sign(payload, \"secret\")",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "path-traversal-file-access",
			Name:                "File path access uses request-controlled input",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "path-traversal", "file"},
			CWE:                 []string{"CWE-22"},
			OWASP:               []string{"A01:2021"},
			Description:         "A file system operation opens a path constructed directly from user input.",
			Rationale:           "Without path sanitization, an attacker can input traversal sequences like `../` to break out of the intended directory and access sensitive system files like `/etc/passwd`.\n\nSource: https://cwe.mitre.org/data/definitions/22.html",
			Remediation:         "Sanitize the input by resolving the absolute path (e.g., using filepath.Clean) and asserting that it strictly starts with the intended, absolute base directory prefix.",
			CompliantExample:    "fs.readFile(path.join(\"/var/www/images\", req.query.file))",
			NoncompliantExample: "fs.readFile(req.query.file)",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "possible-idor-prisma-id-only",
			Name:                "Possible object-level authorization gap",
			Language:            "JavaScript/TypeScript",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "idor", "prisma"},
			CWE:                 []string{"CWE-639"},
			OWASP:               []string{"A01:2021"},
			Description:         "A database record is retrieved or modified using only a primary key ID derived from the request.",
			Rationale:           "Fetching an object by its ID without checking ownership can lead to Insecure Direct Object Reference (IDOR). An attacker could increment the ID to access other users' private records.\n\nSource: https://cwe.mitre.org/data/definitions/639.html",
			Remediation:         "Enforce authorization by including the currently authenticated user's ID in the query filter (e.g., `where: { id: req.params.id, userId: req.user.id }`).",
			CompliantExample:    "prisma.user.findUnique({ where: { email: req.body.email } })",
			NoncompliantExample: "prisma.user.findUnique({ where: { id: req.body.id } })",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "mass-assignment-request-body",
			Name:                "Mass assignment from request body",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"sast", "mass-assignment"},
			CWE:                 []string{"CWE-915"},
			OWASP:               []string{"A08:2021"},
			Description:         "An HTTP request body is directly mapped onto a database model struct during an update.",
			Rationale:           "Mass assignment permits attackers to manipulate HTTP requests to include fields they should not be able to update, such as `isAdmin` or `role`, leading to privilege escalation.\n\nSource: https://cwe.mitre.org/data/definitions/915.html",
			Remediation:         "Create a dedicated Data Transfer Object (DTO) struct that only contains explicitly allowed fields, unmarshal into the DTO, and then map those fields to the model.",
			CompliantExample:    "User.create({ name: userInput })",
			NoncompliantExample: "User.create(req.body)",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "xxe-insecure-xml-parsing",
			Name:                "XML parser resolves external entities (XXE)",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "xxe", "xml"},
			CWE:                 []string{"CWE-611"},
			OWASP:               []string{"A05:2021"},
			Description:         "The XML parser is configured to evaluate external entities within untrusted XML documents.",
			Rationale:           "Evaluating external entities allows an attacker to define entities that reference local files or internal network endpoints, leading to file disclosure or Server-Side Request Forgery (SSRF) when the XML is parsed.\n\nSource: https://cwe.mitre.org/data/definitions/611.html",
			Remediation:         "Disable Document Type Definitions (DTDs) and external entity resolution in the XML parser configuration before processing input.",
			CompliantExample:    "// Go's encoding/xml is safe from XXE by default, avoid third-party wrappers that enable it",
			NoncompliantExample: "parser.SetFeature(\"http://xml.org/sax/features/external-general-entities\", true)",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "dynamic-code-eval",
			Name:                "Dynamic code evaluation of untrusted input",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityCritical,
			Tags:                []string{"sast", "eval", "rce"},
			CWE:                 []string{"CWE-95"},
			OWASP:               []string{"A03:2021"},
			Description:         "The application uses eval() or similar constructs to execute code dynamically derived from user input.",
			Rationale:           "Dynamically evaluating untrusted input acts as a direct conduit for Remote Code Execution (RCE). Attackers can inject arbitrary application code, completely compromising the application context.\n\nSource: https://cwe.mitre.org/data/definitions/95.html",
			Remediation:         "Remove the eval() call. If parsing dynamic expressions is required, use a safe, specialized parser library instead of arbitrary code execution.",
			CompliantExample:    "parseInt(req.query.num)",
			NoncompliantExample: "eval(req.query.code)",
			RemediationEffort:   60,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "dom-xss-inner-html",
			Name:                "DOM sink assigns untrusted data to innerHTML",
			Language:            "JavaScript/TypeScript",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "xss", "dom"},
			CWE:                 []string{"CWE-79"},
			OWASP:               []string{"A03:2021"},
			Description:         "Untrusted data is written directly to the DOM using innerHTML or similar APIs.",
			Rationale:           "Writing unsanitized data to the DOM circumvents browser security. If the input contains HTML tags (like `<script>` or event handlers), the browser will execute them, leading to DOM-based XSS.\n\nSource: https://cwe.mitre.org/data/definitions/79.html",
			Remediation:         "Assign text to elements using textContent or innerText instead, which safely escapes HTML tags. If rich text is required, sanitize it via DOMPurify first.",
			CompliantExample:    "element.innerText = location.hash",
			NoncompliantExample: "element.innerHTML = location.hash",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "nosql-injection-request",
			Name:                "NoSQL query built from request data",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "nosql-injection"},
			CWE:                 []string{"CWE-943"},
			OWASP:               []string{"A03:2021"},
			Description:         "A MongoDB or NoSQL query dynamically incorporates untrusted request parameters as query operators.",
			Rationale:           "NoSQL injection occurs when attackers pass query operators (e.g., `{\"$ne\": null}`) inside JSON inputs instead of plain strings. This can bypass authentication filters or extract unauthorized records.\n\nSource: https://cwe.mitre.org/data/definitions/943.html",
			Remediation:         "Strictly typecast query parameters (e.g., explicitly convert them to Strings) or use schema validation to reject objects containing query operators where a string is expected.",
			CompliantExample:    "db.collection('users').find({ username: String(userInput) })",
			NoncompliantExample: "db.collection('users').find({ username: req.body.username })",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "ldap-injection",
			Name:                "LDAP search filter built from untrusted input",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "ldap-injection"},
			CWE:                 []string{"CWE-90"},
			OWASP:               []string{"A03:2021"},
			Description:         "An LDAP query string is concatenated with unescaped user input.",
			Rationale:           "Without proper escaping, an attacker can insert LDAP filter characters (like `*`, `(`, `)`, `\\`) to alter the query logic, bypassing authentication or retrieving unauthorized directory information.\n\nSource: https://cwe.mitre.org/data/definitions/90.html",
			Remediation:         "Use a dedicated LDAP escaping function (per RFC 4515) to sanitize all user-supplied input before embedding it into the LDAP search filter.",
			CompliantExample:    "ldap.search(\"ou=users\", \"(uid=\" + ldap.filter.escape(req.body.username) + \")\")",
			NoncompliantExample: "ldap.search(\"ou=users\", \"(uid=\" + req.body.username + \")\")",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "open-redirect-user-url",
			Name:                "Redirect target is request-controlled",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"sast", "open-redirect"},
			CWE:                 []string{"CWE-601"},
			OWASP:               []string{"A01:2021"},
			Description:         "An HTTP redirect response uses a destination URL supplied directly by the user.",
			Rationale:           "Unvalidated redirects can be used in phishing campaigns. Attackers provide a trusted application's link that silently bounces the victim to a malicious site, lending credibility to the attack.\n\nSource: https://cwe.mitre.org/data/definitions/601.html",
			Remediation:         "Validate the target URL. Ensure it is a relative path or matches a strictly enforced allowlist of trusted domains before issuing the redirect.",
			CompliantExample:    "if isValidRelativePath(target) { http.Redirect(w, r, target, 302) }",
			NoncompliantExample: "http.Redirect(w, r, req.URL.Query().Get(\"next\"), 302)",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "insecure-randomness-security-context",
			Name:                "Weak PRNG used in a security context",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"sast", "crypto", "randomness"},
			CWE:                 []string{"CWE-338"},
			OWASP:               []string{"A02:2021"},
			Description:         "A non-cryptographic pseudo-random number generator is used to create a security token.",
			Rationale:           "Standard PRNGs (like `math/rand`) are deterministic and predictable. If used to generate session IDs, password reset tokens, or cryptographic keys, attackers can guess the values and compromise the system.\n\nSource: https://cwe.mitre.org/data/definitions/338.html",
			Remediation:         "Always use a cryptographically secure pseudo-random number generator (CSPRNG), such as Go's `crypto/rand` package, for any security-sensitive operations.",
			CompliantExample:    "b := make([]byte, 32); rand.Read(b) // from crypto/rand",
			NoncompliantExample: "token := mathrand.Int63() // from math/rand",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "weak-rsa-key-size",
			Name:                "RSA key size below 2048 bits",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"sast", "crypto", "rsa"},
			CWE:                 []string{"CWE-326"},
			OWASP:               []string{"A02:2021"},
			Description:         "An RSA key is generated with an insecurely small bit length.",
			Rationale:           "Advances in computing power have made RSA keys of 1024 bits or less factorable. Attackers can deduce the private key from the public key, breaking the encryption.\n\nSource: https://cwe.mitre.org/data/definitions/326.html",
			Remediation:         "Generate RSA keys with a minimum length of 2048 bits. For long-term security, prefer 3072 bits or migrate to elliptic-curve cryptography (ECC).",
			CompliantExample:    "privateKey, err := rsa.GenerateKey(rand.Reader, 2048)",
			NoncompliantExample: "privateKey, err := rsa.GenerateKey(rand.Reader, 1024)",
			RemediationEffort:   5,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "world-writable-permissions",
			Name:                "World-writable file or directory permissions",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"sast", "permissions"},
			CWE:                 []string{"CWE-732"},
			OWASP:               []string{"A01:2021"},
			Description:         "A file or directory is created with world-writable (0777 or 0666) permissions.",
			Rationale:           "Setting excessively broad permissions allows any user on the system to modify or delete the file. This can lead to privilege escalation if the file is executed or parsed by a privileged process.\n\nSource: https://cwe.mitre.org/data/definitions/732.html",
			Remediation:         "Apply the principle of least privilege. Use restrictive file modes (e.g., 0600 for files, 0700 for directories) so only the owner can access them.",
			CompliantExample:    "os.chmod(path, 0o644)",
			NoncompliantExample: "os.chmod(path, 0o777)",
			RemediationEffort:   5,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "unsafe-c-string-function",
			Name:                "Unsafe C string function (buffer overflow risk)",
			Language:            "C/C++/Objective-C",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"sast", "c-cpp", "buffer-overflow"},
			CWE:                 []string{"CWE-676"},
			OWASP:               []string{"A08:2021"},
			Description:         "The application uses bounded-less string manipulation functions like `strcpy` or `sprintf`.",
			Rationale:           "Functions that do not enforce length limits will write past the end of a buffer if the input is too long. This overwrites adjacent memory, causing crashes or permitting arbitrary code execution via buffer overflows.\n\nSource: https://cwe.mitre.org/data/definitions/676.html",
			Remediation:         "Replace unbounded functions with their bounded equivalents (e.g., use `strncpy` or `snprintf`), ensuring the size parameter accurately reflects the destination buffer's capacity.",
			CompliantExample:    "snprintf(dest, sizeof(dest), \"%s\", src);",
			NoncompliantExample: "strcpy(dest, src);",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "xpath-injection",
			Name:                "XPath query built from untrusted input",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityHigh,
			Tags:                []string{"sast", "xpath-injection"},
			CWE:                 []string{"CWE-643"},
			OWASP:               []string{"A03:2021"},
			Description:         "An XPath expression is dynamically constructed using untrusted input strings.",
			Rationale:           "Concatenating strings to form XPath queries allows an attacker to inject XPath syntax. This can bypass authentication checks or allow extraction of unauthorized XML nodes.\n\nSource: https://cwe.mitre.org/data/definitions/643.html",
			Remediation:         "Use precompiled XPath expressions with variable binding functions if the library supports it, or stringently sanitize the input to allow only alphanumeric characters before incorporation.",
			CompliantExample:    "xpath.evaluate(\"//user[username=$user]\", doc, resolver, type, null)",
			NoncompliantExample: "xpath.evaluate(\"//user[username='\" + user + \"']\", doc, resolver, type, null)",
			RemediationEffort:   30,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "redos-vulnerable-regex",
			Name:                "Regular expression vulnerable to catastrophic backtracking (ReDoS)",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"sast", "redos", "regex"},
			CWE:                 []string{"CWE-1333"},
			OWASP:               []string{"A03:2021"},
			Description:         "A regular expression contains nested quantifiers making it vulnerable to catastrophic backtracking.",
			Rationale:           "If a regex parses untrusted input and uses overlapping capturing groups with repetitive quantifiers (like `(a+)+`), an attacker can craft a payload that takes exponential time to evaluate, causing a Denial of Service (ReDoS).\n\nSource: https://cwe.mitre.org/data/definitions/1333.html",
			Remediation:         "Refactor the regular expression to avoid nested quantifiers. In Go, the `regexp` package guarantees linear time execution, making it immune to ReDoS, but this rule flags patterns that are dangerous if ported or used in client-side JS.",
			CompliantExample:    "re := regexp.MustCompile(`^[a-zA-Z]+$`)",
			NoncompliantExample: "re := regexp.MustCompile(`^([a-zA-Z]+)*$`)",
			RemediationEffort:   60,
			Detection:           rule.DetectionPattern,
		},
		{
			Key:                 "insecure-temp-file",
			Name:                "Insecure temporary file",
			Language:            "General",
			Type:                rule.TypeVulnerability,
			Qualities:           []rule.Quality{rule.QualitySecurity},
			DefaultSeverity:     shared.SeverityMedium,
			Tags:                []string{"sast", "temp-file"},
			CWE:                 []string{"CWE-377"},
			OWASP:               []string{"A01:2021"},
			Description:         "A temporary file is created in a shared directory with predictable names or insecure permissions.",
			Rationale:           "Creating temp files predictably allows local attackers to pre-create the file or symlink it, leading to file overwrite vulnerabilities or data leakage via race conditions.\n\nSource: https://cwe.mitre.org/data/definitions/377.html",
			Remediation:         "Use secure APIs like `os.CreateTemp` which generate a randomized file name and open the file with strict, exclusive creation flags (O_EXCL).",
			CompliantExample:    "f, err := os.CreateTemp(\"\", \"prefix-*\")",
			NoncompliantExample: "f, err := os.Create(\"/tmp/fixed_temp_file.txt\")",
			RemediationEffort:   15,
			Detection:           rule.DetectionPattern,
		},
	}
}
